components:
  schemas:
    tmp0:
      properties:
        incidentId: {type: string}
        incidentLongId: {type: string}
        incident_applicationName: {type: string}
        incident_applicationPath: {type: string}
        incident_blockedStatus: {type: string}
        incident_customAttributeGroup: {type: string}
        incident_dataOwner: {type: string}
        incident_detectionDate: {type: string}
        incident_detectionServer: {type: string}
        incident_eventDate: {type: string}
        incident_file: {type: string}
        incident_incidentCreationDate: {type: string}
        incident_incidentHistory_actionType__value_1: {type: string}
        incident_incidentHistory_actionType_actionTypeId: {type: string}
        incident_incidentHistory_date: {type: string}
        incident_incidentHistory_detail: {type: string}
        incident_incidentHistory_user: {type: string}
        incident_incidentId: {type: string}
        incident_incidentLongId: {type: string}
        incident_isHTTPS: {type: string}
        incident_machineIP: {type: string}
        incident_machineName: {type: string}
        incident_matchCount: {type: string}
        incident_messageBody: {type: string}
        incident_messageBodyContent: {type: string}
        incident_messageHeader_componentId: {type: string}
        incident_messageHeader_componentLongId: {type: string}
        incident_messageHeader_componentType__value_1: {type: string}
        incident_messageHeader_componentType_typeId: {type: string}
        incident_messageHeader_documentFormat: {type: string}
        incident_messageHeader_name: {type: string}
        incident_messageHeader_policyRuleViolation_policyRule_ruleId: {type: string}
        incident_messageHeader_policyRuleViolation_policyRule_ruleName: {type: string}
        incident_messageHeader_policyRuleViolation_violation_documentViolation: {
          type: string}
        incident_messageHeader_policyRuleViolation_violation_fileSizeViolation: {
          type: string}
        incident_messageHeader_policyRuleViolation_violation_imageViolation: {type: string}
        incident_messageHeader_policyRuleViolation_violation_violationText: {type: string}
        incident_messageHeader_ruleViolationCount: {type: string}
        incident_messageSource__value_1: {type: string}
        incident_messageSource_sourceType: {type: string}
        incident_messageType__value_1: {type: string}
        incident_messageType_typeId: {type: string}
        incident_originator_IPAddress: {type: string}
        incident_originator_originatorId: {type: string}
        incident_originator_originatorIdLong: {type: string}
        incident_originator_port: {type: string}
        incident_originator_senderIdentifier: {type: string}
        incident_otherViolatedPolicy: {type: string}
        incident_policy_label: {type: string}
        incident_policy_name: {type: string}
        incident_policy_policyId: {type: string}
        incident_policy_version: {type: string}
        incident_recipient_IPAddress: {type: string}
        incident_recipient_port: {type: string}
        incident_recipient_recipientId: {type: string}
        incident_recipient_recipientIdLong: {type: string}
        incident_recipient_recipientIdentifier: {type: string}
        incident_ruleViolationCount: {type: string}
        incident_severity: {type: string}
        incident_status: {type: string}
        incident_superseded: {type: string}
        incident_uniqueMessageId: {type: string}
        incident_userJustification: {type: string}
        incident_userName: {type: string}
        incident_violatedPolicyRule_ruleId: {type: string}
        incident_violatedPolicyRule_ruleName: {type: string}
        statusCode: {type: string}
      type: object
    tmp1:
      properties:
        incidentId: {type: string}
        incidentLongId: {type: string}
      type: object
    tmp2:
      properties:
        InaccessibleIncidentId: {type: string}
        InaccessibleIncidentLongId: {type: string}
        batchId: {type: string}
        statusCode: {type: string}
      type: object
  securitySchemes:
    BasicAuth: {scheme: basic, type: http}
info:
  contact: {email: frikky@shuffler.io, name: '@frikkylikeme', url: 'https://twitter.com/frikkylikeme'}
  description: Automated generation of Symantec Data Loss Prevention
  title: Symantec Data Loss Prevention
  version: 1.0.0
  x-logo: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAJYAAABkCAYAAABkW8nwAAAOJUlEQVR4nO2df5BcVZXHv+fe7k4yk6TnTbIJPwVFEBAVUXFd0CqUiElPwq+FXUq3ymJlKd1CWcXVlXIpa0HUXfAHuFu7llqSZYkpRTMzLwhIhSChCmUJu4oLuLL8UEMg5PUwmZDp7nvP/vF6ZnqG7pn37rvvvdvNfKqmcvPmnnNP9ztzf99zCYv0LPwj72hdwjNT/5eVgLIqW2RV0CKvLhYdq5c5r38ibxMW6R3eDYCbP8/nZcRijdV76Jb0obyMWHSs3iazzvpcCnkVvEhiJIBGm+e/QNOheHztGn1fjacFFkeFiySgPp36aW1JXkYsOlb3ojo8d+KdLjaF3cXZAK5opmtbPrdsHAB+9Vvecu33D/nN5/unc9f79+ni+IUAKRDn1t9axH0uxcxUwgHle6x8jxu+97c52/UKFmusOfBo+XVQtBxCLEWBxgB6idbv25O3Xd3Gq86x+CEUsWfFsVoUPgTg7+f+XgPNb4UBHQ6olO/N1qGxmyV9tiCLu1DaO0lntR2dJWEIwNJm+qcAqm3ySGj+IQDcsqNWAPCnzef7ANxr2Z7Y9Hy7y773Jg18BMDH0y5LM60rHOzbRRf/7uWEqvYAOKyZPg3A7mb6UgDfnioO4ZQDAHwFwKeb6QcAnJGw/MT0bI3VGB28CJo/r4E3ZVWmIL5b909A+d4OMdm4iC4YfzGrsl2jp2qsxujAxzTTNVJgTd62zKC3yMrYJTGFTgJQbKavA3BMM70TwLeaaQHglmb6NgBTo8IJAL81s9UePeFYfA1E4/TyowLixLxt6QjjHjkUnG0guRvAqc30dxE2h8DsmffPIGwOnaHrm8KGX35AQ7zLiVnB+SC8rzbs1YvLsJrWBWN5m5M2XVtjqZGBH0DQhXnbYYqQahV94KX9LY9uRPv38RyAWjPdD2BVM80Anm2mfwbgoTTsNKUrHUv55dsA8ed525EYxhflUHB1838a7d9HlFGhczjfgrTS8L2dyve4J5wKAAifqw17NR4tvy5vU2zTNX0sNeLdDOA9edthCyLgrofreL7KRSnmHcVtAPDGZvqPMzDNCl3RFDb8gQcJdHredthESODMT45j16+NJ+2dbgqdrrH4Goj66SsPEGhZ3rakgeiqjkg8nHUs3oqS7vcmnf2TNKQ6wQADUgJLS4SB5WGjUT3AC0gCCEeHB5tpPV/GvHHWsXS/N5lleQp4WoD3EtNeMNcguAaIPjCWa9JHsuIjpJQrk5QhisDaS6poNLfo3fvlFXj3KeErKAwF4IV961bMTJA6jZOOVRsu/yHtMjT0/xCJm6TWd9LQ2JNR5eqjA+cK0DkgfDRN+7od5xyr4Xs7CTg8vRL4y6Iur5PnBeMm0sWh6jYA2wB8jIfLp2lJlwP0V53yEwHUR+F0ZnH27/qXEkRfrPFT1/Q1nRoVNnzvIzSzyGoNBj5VqAQ32tY7q4w71/bXJw/tk1IsbX0eHGCs/rOqsd6Hby7jrccVj+i2zYbO1Fh8R/lYre06lQJUqRJk8hnpnL0TAJbxHd4b63XslnJu/WQGM6Ou1bNw6F1FwYkBLw+vOlFr8X8WVW6WlYCycqpWaH3waGlTUPrmtkMXPrlH46m9nQdvR6wSOO7w8KeVY9bMPF9SJEhAKt/blrbtNnGiKQyXaayxTVaC8yzqM2XBz3TfP86MCsWGmVHhnlsHcNhg+Gp0i18KqHdQ5SWnFps7kXv1WvcH10V4B5HI8qSvDbSe7TjTz7nDc8jpU86uk3tTKMB3WdHTKB62cC63WNlHECvCn9Y5rHZONQVv985M37Lk5Or9yvc2A/hQUj2ihAEHNs/9DcI9VUbo7d70y9ALVODdUDPn3RQmdipHvuSfAUhUk2gdznlFoTFSvr+wcczpmiu3prC+fWBjUh0i4cu0SKZ2kBBn8N1eOcsy45JbjcVMP04iL/oKK+isFw5YMseUIma2Dcemda0wLrqGKhzuyOfiWMr3rkWC2lKxOiDPCvJ2KiA8WGqOs26RnFyaQqXUFQvn6kxxCR9ryZQkbMbMwQYjbr9/8sok8rzV3eYwc8dqjJSvTLL9RBAdTes6njB+A8K4m/cA8DrkscEqmA88CgjrKvrGcO3rWuMpUyPq/erZhXPlQ+aOpQVfZSqroJ+jDft/N0+WxwAsAfBehHGiXkY6n/HhBLKzGsCCwCZTRRJyRQI7UiVzx5KQR5rKFifGjprn1+0+y1KEke/abFox5g8AXhMjPyM89n4QbWKGUiX4JcBfNTWmMez9t6lsmmTqWDxaTtQ80cUdwyMCC68L1QC8I0n5CL+vuHvFAgDLER42LaKNc8lK9ZOmBmmpjjOVTZNsayymUxIIL/RXHWXB8ecAjGsHmO0VS3XsJyH70tRvSqaOVWf+vqmsmKh+euFciBIl+EoA8/XT5pNLb7858w3Gotfkv+Y7l8wM4h0oSClMtxxvW6AZnKKGmZA/83EkgLjzYKY13feiZJJDVeNBTeP0svEAIC2y8/SJsvEIRghcvXCuaZ5BtOh9/Qg74lF4KUb5rXwH4eJ0JFQY5jE2gumDJnJpkpljKdCQqSytDx6NKXITgP+IkO9wAHdHyGfyR3E7gL+MIyCYjTrxWtNbTeTSJDPHIso85NAHAfwqQr6zAcz3Qt9vWH7szyuFMNp+LCScGxlm2ek710RIJVjkRfT4ozcgbBrbcWfMMidgOhJ8cL/x+iePDBrPD6aBc6OJuRB05MOkHYi6nveLNs8+Y1BenMnTWdAXoJWC6YbFRceKg4B4IqGK/Yg2DXESgP+c8+xLMcsitF45YoAU+jYTuQbUomPFg5+zoKQGIIqDntaSjrsE9HTM/G1hwm9M5IjkoI3ybeG8YzHj95ZUvT1ivpOb/8adGzo1Zv62MKSpgyYKWGIb5x0LzKZzSHMZR+cOeiuPAigB+EEM3aeg/bUk8WFl1pSSdiqug/uOJUTJoraDiHaSJm6tEXeerSMFmh37ITJMTsXLct6xCGz7vOCnIuSJU6bVK90U42hD0cCmHUlx3rFg/kXPxy8t6jJePG4HEb/eTNBSU2wJ5x2LidK4F+fNlvRsgfWQjRR1kDELBiWa5rCN846lZ0JR22aDBR1pbKM5y0SooOtPWbYjERkuQvNeEzmZ8CTMPNyRUH4nwj311uAdx5h13AHg5XEr82i2yMyxBOOmrMqKQZJDEZdZs2KKl8dPNRFTwD66ONGaqnUycyxZp1sWztUe3r78j2za0sIFCWSNZsjnQyu+zkROgh+xbEpisutj9ZWMO5dKF86xaUoLTwP435R0x0fgvUZynKjmTYXs9mOFMTrNZIk227RlDqctnOUVWL/BtD5SPt9UVsjC1yyaYoWMR4X8r8aSo4Mn2bSkhXEA/x5T5h7bRrAQW0xlXYyonKljCS3+wVS2ThxlN6gpfxEz/7/YNkCG65M9Q6aORRv3G+9UkOnbGueKlUdsFlwfHTS5KxoAoAGb0aat4fwEaSt8R/nYFNVH7cc9ZbtgJh23KZ6GwNYvXLBB9o7FuNlU1HIs+LlcBqBTFJtWjPtC7VAjA3dJ0FojWaUPFSrV623aY4vMHUtIYexYAFD3vaRblefjogh5vmC1REHrTEWlFHEPemRG5o5F6198HJp/aCovgOMbfnmXTZta2IFwlNiJ/Qjjb1lB+QNRzjR2xJGLEtqSSx9L6NJfJ5EniD+xZUsbVgLw2zz/CSyuWzZGvYsBMu60u04ujkXnPr9XQz+WRIca9X5ky542DCE8TvV1AFcAWANgvS3l/JOVg0QwDpDSJFJMiLzI+wKBRHedKKBaqgRphoRMBRt3BzkS374juU43KPXKIGRxkMAAbx+wtWkvE2r+yoML55ofwdq5WA1zydWxSpuCxOEbNdN/1X0v6WnpTFC+xxIy0WkaBq6iobFHLJmUGi5MkCbuKwjgtbVhr2rBllTg4cP7asMrrdz1U6gEVvfYp0XujiUrwYet6JEoq9GBf7OhyybhvdGHJpKEIJ9Cp7AHLC1ydywAYKDjZd2xILpM+R6zv/oEK/oSonxvh5ZibjwIM11K7ylWAic+VxScGVk0RryHScBmp9SXlcA42FtSar43aXPHgtgQCCJLN4ZmgDOOBQDK924HYLzhra1O4Jni2uD19HbUbeptR2N04Goiuta+Zv0lWRn7O/t608MpxwKs3w89jQCuQk1/m84fq9rWzaOr31bXtZ1SyiixIWKhNT9e3Fg90bbetHHRsb6BcLY7FTTwZIH4fNpQTXSjA28fPEppnKM13yAlUrksSSmMlTYFA2noThvnHAsA2F99goZ6PIuyFNS4gNxNwANM9Bup+TEwT0CKOkD9Da3XEPGbiel4Jj6ZQO/Mwi7A/dn1+XDW8BQ6812FmGyspgs63nLmPM46FgCwv+IEjUImNZcrKECXKoHM246kODGP1QmqjD8hWDsXajotlMJkLzgV4LhjAQANjT2Z5Nq1bkEpvFDaFJjHbnAMp5vCuaQ1FZE7zDfKoWqUgHBdg/M1ViuiLyiywkN522ETwTij15wK6LIaawreCqn7vUR7ufKGwVcXKtUv5m1HWnSlY02hRr1/BuGjedsRFzERLHEt7JBtutqxAKCxffBSzfytDE5KJ4a13lXYOHZm3nZkQdc7Vit133tCAMfnbUcrSmG/ELi+MBT8U962ZElPORYQnoBp1OTP875qTSnUpeDNcqga687CXqHnHKsV3nrUMt03cT0In8ikPMb9LHB9cUOwPYvyXKanHasVHhl4iya6XBEut9kfU8CLBP5wgRoP0oYDL9jS2+28ahyrFb5zbT/qeoXmxg2KsU5KxIlxuoNJ3yprha046sVDWWwg7Eb+H08tB7lYukb5AAAAAElFTkSuQmCC
openapi: 3.0.2
paths:
  tmp0:
    post:
      description: Get details about a given incident
      parameters:
      - description: Incident ID to get information about
        example: ''
        in: body
        name: Incident ID
        required: true
        schema: {type: string}
      responses:
        '200':
          content:
            application/json:
              schema: {$ref: '#/components/schemas/tmp0'}
          description: Successful request
      summary: Symantec DLP Get Incident
  tmp1:
    post:
      description: Retrieve all incidents relating to a given report ID
      parameters:
      - description: Specifies the ID of the saved report to execute on the Enforce
          Server. This report must be created using the Enforce Server administration
          console before executing the Web Service call. There is no mechanism to
          create a saved report by the Incident Reporting and Update API Web Service.
        example: ''
        in: body
        name: Report ID
        required: true
        schema: {type: string}
      - description: A common datetime formatted string, used to filter incidents
          on creation time
        example: ''
        in: query
        name: Incident Creation Date Later Than
        required: false
        schema: {type: string}
      responses:
        '200':
          content:
            application/json:
              schema: {$ref: '#/components/schemas/tmp1'}
          description: Successful request
      summary: Symantec DLP List Incidents By Report ID
  tmp2:
    post:
      description: Update Incident
      parameters:
      - description: CSV list of incidents to update
        example: ''
        in: query
        name: Incident IDs
        required: true
        schema: {type: string}
      - description: Change the Severity of an Incident
        example: 'valid values: LOW, MEDIUM, HIGH, INFO'
        in: query
        name: Severity
        required: false
        schema: {type: string}
      - description: User-defined status from the Enforce server for an incident
        example: ''
        in: query
        name: Status
        required: false
        schema: {type: string}
      - description: Add a note to the incident
        example: ''
        in: query
        name: Note Text
        required: false
        schema: {type: string}
      - description: Date stamp for the note. If blank, defaults to today's date
        example: ''
        in: query
        name: Note Date
        required: false
        schema: {type: string}
      - description: Custom attribute name defined on Enforce server, requires Custom
          Attribute Value to be defined
        example: ''
        in: query
        name: Custom Attribute Name
        required: false
        schema: {type: string}
      - description: Value for the custom attribute, requires Custom Attribute Name
          to be defined
        example: ''
        in: query
        name: Custom Attribute Value
        required: false
        schema: {type: string}
      - description: Label the incident with a Data Owner Name
        example: ''
        in: query
        name: Data Owner Name
        required: false
        schema: {type: string}
      - description: Label the incident with a Data Owner Email
        example: ''
        in: query
        name: Data Owner Email
        required: false
        schema: {type: string}
      - description: Change the Status of the Remediation of the Incident
        example: 'Valid values: BLOCKED, CONTENT_REMOVED, CUSTOM_ACTION_ON_EMAIL,
          EMAIL_APPROVED, EMAIL_BLOCKED, EMAIL_MESSAGE_EXPUNGED, EMAIL_QUARANTINED,
          ENDPOINT_BLOCK, ENDPOINT_NOTIFY, ENDPOINT_FILE_QUARANTINED, ENDPOINT_FILE_QUARANTINE_FAILED,
          ENDPOINT_NOTIFY_CANCEL_ALLOW, ENDPOINT_NOTIFY_CANCEL_BLOCK, ENDPOINT_NOTIFY_CANCEL_TIMEOUT_ALLOW,
          ENDPOINT_NOTIFY_CANCEL_TIMEOUT_BLOCK, FLEX_RESPONSE_ERROR, FLEX_RESPONSE_EXECUTED,
          FLEX_RESPONSE_REQUESTED, MESSAGE_MODIFIED, PASSED, PLACE_HOLDER_DO_NOT_USE,
          PROTECT_FILE_COPIED, PROTECT_FILE_DELETED, PROTECT_FILE_QUARANTINED, PROTECT_REMEDIATION_ERROR,
          REST_ENCRYTPED, REST_PERFORMED_DRM, REST_PERFORMED_BREAK_LINKS, REST_PERFORMED_CUSTOM_ACTION'
        in: query
        name: Remediation Status
        required: false
        schema: {type: string}
      - description: Location of remediation
        example: ''
        in: query
        name: Remediation Location
        required: false
        schema: {type: string}
      responses:
        '200':
          content:
            application/json:
              schema: {$ref: '#/components/schemas/tmp2'}
          description: Successful request
      summary: Symantec DLP Update Incidents
tags:
- {name: Investigation}
