components:
  schemas:
    tmp0:
      properties:
        ai_score: {type: string}
        date: {type: string}
        filesize: {type: string}
        first_seen: {type: string}
        md5: {type: string}
        sha1: {type: string}
        sha256: {type: string}
        tag_name_etc_tag: {type: string}
        tag_name_etc_type: {type: string}
        taglist: {type: string}
        version: {type: string}
      type: object
    tmp1:
      properties:
        date: {type: string}
        detected_communicating_file_list_date: {type: string}
        detected_communicating_file_list_sha256: {type: string}
        detected_communicating_file_total: {type: string}
        detected_downloaded_file_list_date: {type: string}
        detected_downloaded_file_list_sha256: {type: string}
        detected_downloaded_file_total: {type: string}
        detected_url_list_date: {type: string}
        detected_url_list_positives: {type: string}
        detected_url_list_total: {type: string}
        detected_url_list_url: {type: string}
        detected_url_total: {type: string}
        hostname: {type: string}
        ip_history_list_cc: {type: string}
        ip_history_list_city: {type: string}
        ip_history_list_cname: {type: string}
        ip_history_list_date: {type: string}
        ip_history_list_ip: {type: string}
        ip_history_total: {type: string}
        location_cc: {type: string}
        location_city: {type: string}
        location_cname: {type: string}
        location_iplist: {type: string}
        location_latitude: {type: string}
        location_longitude: {type: string}
        undetected_communicating_file_list_date: {type: string}
        undetected_communicating_file_list_sha256: {type: string}
        undetected_communicating_file_total: {type: string}
        undetected_downloaded_file_list_date: {type: string}
        undetected_downloaded_file_list_sha256: {type: string}
        undetected_downloaded_file_total: {type: string}
        undetected_url_list_date: {type: string}
        undetected_url_list_url: {type: string}
        undetected_url_total: {type: string}
        version: {type: string}
        view_count: {type: string}
        whois: {type: string}
      type: object
    tmp2:
      properties:
        date: {type: string}
        ip: {type: string}
        location_cc: {type: string}
        location_city: {type: string}
        location_cname: {type: string}
        location_latitude: {type: string}
        location_longitude: {type: string}
        version: {type: string}
        view_count: {type: string}
        whois: {type: string}
      type: object
    tmp3:
      properties:
        date: {type: string}
        same_hostname: {type: string}
        smishing: {type: string}
        url: {type: string}
        version: {type: string}
        view_count: {type: string}
      type: object
  securitySchemes: {}
info:
  contact: {email: frikky@shuffler.io, name: '@frikkylikeme', url: 'https://twitter.com/frikkylikeme'}
  description: Automated generation of Saint Security Malwares
  title: Saint Security Malwares
  version: 1.0.0
  x-logo: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAJYAAABkCAYAAABkW8nwAAANEklEQVR4nO2dTXAU1xHH//1mVgKsGFeB7EQC5MJl34NFrsE+pSoxN1OOzg4m+GQVLgphaVlAsik7+EaB46uJyzkFSI5BOSPkU6pSuGxHEogDkJgg8zUzr3OY7+/ZD7Er0b+LtPPx5u1sT79+3f16AEEQBEEQBEEQBEEQBEEQBEEQBEEQBKEpGEzMUAwm/zMAMEN1t2fCmuZNhuH/7wuVILRNTJheaezuYld6DlHZbUCg8F9bM7ZPvtHN/vQSZltnMxOIuEN9cW0TYiZ4bY4c3QOYY7CtXe4RJgAbILqAh/1zuD31N8DVHME5Va/VwjmZzUT/aqoz+BKBuPK96fA97BVatwuSN4SZGERE0G21+eIHvwSZh2BZP03tNwA4AGqGguW411HGPSydeK3la3aKnfVRPLLOQqnLWDr5ftPnc12BGlXvHSEU6lWFUVeEyv0KyBeswYMD2Lj1PBx7KLXP/4F9TDqEhenZZi8eY+TIGGwaBxGBOf+mGcSwAVCGsXxjZrRJDeC2MTxxJSasWe2W4QtWM+ckGZ6Yy92XbK/o2E7gX69FjZpvY20Y3J8pVEBcqJTRiApVy1Ntm8a9BtJfglW4zWHKFCoA2HZ0KrKnqjZ2284TqpZo0sLgVmaU7VkxpXDd/R1bHKZV7jRZW2OVrr90/FL0c5WhMHXNoXdfyT7QEyjSlNqWOtbUYN5LW4+8jOpDRWeHEza9724DW05lP5RZtPTj2c2f0gzVh+VMAu0S+7G3T14uP9O4h8c/7GnFAI6ds2NyP2jz+ewDfYEyASKC4W2rGRla0XGP7TO+wBOyP1IQ/KecsOHuBbxc/0VX+tEDKP9HDqSKmWBgc+mZSydew60zK61eOBBkx9mfLShRvKfTKTjEHx77lIGRI5W0bcchhwAzHM7vW2eie7vSpy4Raiwm94vH1HLOOG6oax25+uDBAQA59o0Zvz5z6OcusocsR4PVWx3pX7MUTTq6pUW7RGBjBbbRjqkL4Q9nA2zEb4jqv4fFk2No4wkMfEh9z83mH2UDhr6GGzOjuDEziuvTu7E4M8o3pnfD5PcDWyv51wDg8BBeOvbXVvvXHgnbZ/sHHzNDeZOaJ6e1jIomSpbNyhVdRgWTDjNm72yffCM1EyQncbJ9Orh8i6TssjwXw4P/7I8cw8G5C7iMkSOfwq6Ng2xP0+p4Px8+fsHrJqF9R2jrML9OL9V34btGx9wDDCYypj4rPIjUKOA7lpP7iKDUuXCDkTqkkgO5YNIRH+u0U8/tCDOjv+9rfHfsUuYxTRDrNBNnymh//zxuFNhwCx+ex/CE66KI+qBSdliXvdrMjEfWWQwe3NOOTRqFQIxFFAvWjkkA2BVEK6IoZiyeKDyfcCL2OSlozFCeVGQ6xc3Ygdv8TZGOMDRgKBhYxnfHfuc5zAq/UxlhB03kWuSWfbFyg4+1Ew3c9STusN+807QdWHGg0aMUTYKQoa22nBqiDUcvABPBJtoGYIiYXsT7QNo5rgKHJvlDUUK6/Sk08x/dzx3UAKw519lZUzdLU1G8KBKIKde/1W248xqzcooOacq0l0r6FBOqkSNj2LTyBQBA0Sz6awfQXzsAx/wCxAQHf8hqw/TVGG2f+g00kBnaIIewNF1dg1QlaRcld5eO8UxgpJ2ovQQxBabE8MRcS6GeZJPNDO+UEQnJe5iTDE/MwaELuJ4Zi50D8CkAYOjoFRhqJRqzDW0s1j+HgeypfPE0WijDVATLYTAxBg8O4NaZH9Hr7oeRo3tgM3B9+jiYCduOXgEQxonN2jzuYxy3GisgJmjnJ5GzyZXml46/Cua9mWMvEfnyJ1mSLWJrT6syoe+5WYzUz5Wc0V2YCTZ/EmhXIteHaNbmsei5f1Y2HUMfzwJwA9aKzmN4Ys6TEXYFy7JeLbgIw6R5wFXBks/dAqZyH0h/Vm/nuAF6hefffSb6kcGUUjp3Di/DsN28fzChr/8fQDhMu0LiOPvdL53jaV9oBP6ktvKtnlayXCFu1KE3R4CNW2IhscCms61d2Hb4Kl6cnMf2yctYnBl1Z07E+HbqavScUPs4pjtLS2KoazIEdpCaocDE2DC4H71sZyVnjkQEZdyD03cFrObg6AHsrAcTEQbHkgMiw5qdM7Oi2Q6k8Ao+lqNdY7daWlJXsHAVZMRlgZmh1De4eeIAFhr7oXARj+1zfliHQAzL0XUvdOX5qLx4IFE6JcVU860logmlhFmgPXV/+ebxecBGbHEIQ8f0kDtbZBAxtp77GYYn5kB0oeGaSp7x7scDNWnohLvhW8yvx2T/nsG1tXrq/hKIYZjLgHov2GhCATruGfCHy/5/HwIAPHj28/DwoDUiQKfd/fFMwieWxP/UsLELoZ4qLB7fi5H6ZxiemINZm8dCYxQACI3wmOXp3Rg5MgZt7sID/i3uHF72d4W6rZoTlNFjanvNowwVNYJ7ivu33CC/be0Kcuei7KyPwqZxPLDewe2T3wDhmodWMvJFY3USizRgncXIkdOrncZelTpDNQjay8YYxZZTQ9iAWQx9wLF08UcW0Gf8HjdmrsEbzXx31Cov9RACFM3CUK9DOxo6mn9mu1kIth7vbgdDGklfpTvElWnVmMIJk//z2FkfBbtVVVrqpeBOjmrml7AcDQcRs8N7rklTRq7dmsZPickf3hx7QGaFbRK6cy7Ed0TGvpIcqR6EAOCrr7IfiXItxMY4IKGctrE2ub4fQ11LebVrai1MiJKjFgPAvn3Zj4Sb6Jd6kiI49hBemPi1OEnbpHbf/bt4cgwKF2Pmh5URSus9uBnlooig8dD5snCMV0ZgWErcsAP4Xut1jKvabn90DUyzuUfVnM1+nrvEDYUqhLUblJ7PXYumagriHO0sqpZdVmCdECyxx8KH5+HkDHOWpbHl1BCLb7QTuPd4qXEaZm0eNUWo1dadKyf+hfI0lgFg0/23ZBjsCOE9/PHRJ7A0w7LW3Yw7LlisshdUOgA0j2HHVP7sUWie2x9dQx8ahQ7qNUpCBauCJV42cguxCa3z/czFWD7cOiEuWEuN01DJ2WEinNirkfi1C0GRa8iba8JRWom00bg0fSi+wQs7+E+T1p8BoKCUoNAuzEvHPsWNmVE81msvsJNDlnBkPzW+Q89yNAYPPtNuKUHBgyN1EvrUuglFZ9UgZRhGvBKJu3TMqw4DXVzXSmiKaIC/owV2u4vKdCE8uOOO+f7zQ5FKxV4tAEmjEYrIFo5bZ1ZStdwT0Mjk26vTJWE9kK91iA7l7gPc1dMyQxRyyBQsZigsTM+mbK0klv54VXolrHkyBcvLuyH8OFBcFpJ0euWGIKA4g5Rx5/Byqipx7Ow2p8erUO1O6A3KZ3akKUz6T4Qc2p4ee83V1o//RnApX/7F5BZIJYRlGbMq8fpvidpyaggb7lYMVntyaWV4nB9ZZzE8kdocXk+xe75XJadXS0U+pZRrLG38Pb3RTmsv39HnL7Ou1RRqhip/nUmLBIKUVyVH6CblGmsTf49H/qERLaVJFyaU+jlG6yhiL1SngjZRXqmdZJluTSBNmb6s69O70V87AEAK4z6lVFtiT0RQ0Lmpy+njGcBcoY0krGtyNVYQnH6g3VcMOUa2UN279a/c1s2+r7MbN/JdGFUJXjppynDbg+QKVhCcruFVN2boDYXJNx0UvR9mZWPOu3n8Fz8xKinNrMUGfdp1URi2u+xW6CnKf1ULu2Li57/pwAtSey/ryfZnlVUpGZ6Yy30FrTbewc0TV7N3ej0ZnriyBmsePBWUGe8E5YwWechXrabDxtI0XdFSPUy2YIV1GsI3KjRXSqvU5ildqt9M/rf47XuObMHKLFuUGLKKh6BSbVK6RtFuolCGDIc9R67Gyqt7JAhVyB7fiPhNBmPb0SnkTbgMAGzcW72uCWuZfHfD8wc3gXlv/pmGAuvLq9IrYc2TPyvcsPVSqQPz0X9PF+4Xnlqyh8LB+gC0NVA4tyOn7jlH5aUCQopsjWXqv5Smu3w/49d5EKESUqQXrP6q/iwUbQ6yQ/24XoAJKKOBNghenlh6XMVl/C2kOMeunxdrDE2Bsr4SrE3NdsG7Rl0VrtFkxa3ltHU37Vv9+SuKd/qfeDvms/Ljev6XI4fw8E5bRjtxtZKThIrL+Etenp35w3FEmFIPj99ukJad19fQkewXr20WaujC6IViBcvRzS8Q7m6tWLVvH5zg6d0+eTn3PXq+BiP1v2jguaUV0ZXqxlulrVS/XPqHi2+z87UeO0V9jewr7W9OCxEByCrL7eWzNRU6K6twvVpZvRFMIKI9CH9CTQO6Fu0F3Jvm/uWFE58DYeC5rVihv25RWYlrArg7sJxxRpR0jYl2+9EOdzcv45mVnHZqwA/qZmbAPvqQaToHo32/NIOIzPo8gOz+9EyFiOgT0IF67wkt1057lNFe4mI5dloXXuOSd70nXgdDavYLgiAIgiAIgiAIgiAIgiAIgiAIgiAIgvDU83/AyBvvOXVQZQAAAABJRU5ErkJggg==
openapi: 3.0.2
paths:
  tmp0:
    post:
      description: Look up information about a Hash in Malwares
      parameters:
      - description: The hash to look up
        example: 7c7bbbc8710970b1e9c228c9519a265429536b4e0ad988daae33b266303ba592
        in: query
        name: Hash
        required: true
        schema: {type: string}
      responses:
        '200':
          content:
            application/json:
              schema: {$ref: '#/components/schemas/tmp0'}
          description: Successful request
      summary: Malwares Hash Info
  tmp1:
    post:
      description: Look up information about a Hostname in Malwares
      parameters:
      - description: The hostname to look up
        example: google.com
        in: query
        name: Hostname
        required: true
        schema: {type: string}
      responses:
        '200':
          content:
            application/json:
              schema: {$ref: '#/components/schemas/tmp1'}
          description: Successful request
      summary: Malwares Hostname Info
  tmp2:
    post:
      description: Look up information about an IP in Malwares
      parameters:
      - description: The IP to look up
        example: 192.168.0.1
        in: query
        name: IP
        required: true
        schema: {type: string}
      responses:
        '200':
          content:
            application/json:
              schema: {$ref: '#/components/schemas/tmp2'}
          description: Successful request
      summary: Malwares IP Info
  tmp3:
    post:
      description: Look up information about a URL in Malwares
      parameters:
      - description: The URL to look up
        example: http://google.com
        in: query
        name: URL
        required: true
        schema: {type: string}
      responses:
        '200':
          content:
            application/json:
              schema: {$ref: '#/components/schemas/tmp3'}
          description: Successful request
      summary: Malwares URL Info
tags:
- {name: Investigation}
