components:
  schemas:
    tmp0:
      properties:
        meta: {type: string}
        namespace: {type: string}
        rule: {type: string}
        strings: {type: string}
        tags: {type: string}
      type: object
  securitySchemes: {}
info:
  contact: {email: frikky@shuffler.io, name: '@frikkylikeme', url: 'https://twitter.com/frikkylikeme'}
  description: Automated generation of Swimlane Malware Detection
  title: Swimlane Malware Detection
  version: 1.0.0
  x-logo: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAFYAAABWCAQAAAD/X6l8AAAGPklEQVR4nO1aWWgfRRz+9t8cpVWbaktRolSL2kspRgL6oCStCCIeSEE8Cl4PWhAUJWqkICihPkhffBD6oIJXQdCA1uNNEMGTIgZFGmpSWmnVIm0Smyb5fJjd2Zmdc49/EOr3J9nZmd/x7cxvjp1Z4CzFCGj5TWJJUw6S2ha4eN5alTWvTGtOwRuWit2qCoisLZV9VsLpnM1TjMV2/SkqoHzDSDdTWFbB4YyqVdJ7WbLULpWRGIkYlInZXsGxYhtqYP7Um+O14snegEmgpwGiGYiLAeBH3NiYyRQJCA5Hd6ZY7Badrf4AqoHgtsapknKMiKyxOKqo36kCFCKYxMTso0D7qErLu8KSMTXLdlJVaAS5hGu23TxLeIoautrPN85DiOy2+kRK4AF/cShOCKzB742xcWMTxoJ8IsguVtCGO1n0dJs0Pc2keLqE3eiaTdCeOk4AfIDbUb9muxvj5MR3AO7Ib5/zyfrJ9jXAJoBrZGoQAG71yfrJHmmCjh8/y9R1AHCtT9ZP9lADbAIYAXAhAGAWAM7UsUWkS7k81SxA8GuS5FqCeN9H5j8xGuQesAbH3LKl9g3WVecUCw/VKLIdAMTTjzdBR0MCYEO0dIjsIDBfi04YYwCAuxqx1dYuplv3TwmRZDsCZKe50fMgqwl+E0c2gPAqogunRcQmAObk/qVN0bahZMotxYxWSsS+NIY72CwAbEpvBNUBh9XlUeb/MVZwv4pLQ8s6QmmyL2xbxunP1sw+2dwyloZplNg3yBI+lWLYhWSV8ob2DRproLoeYmcwxZhbpcPI+TZg9lLDejMYKAwzERHrk22VGLLs8KkS3O8lMOgZS90P5vT4Wio5lGepDZArTeEcC1lFwNZurqdcjmkjr0MuXB1vXqoxWZoH4F4h0ynsP+/w7IS7LacseYE19jwAHMhsHrZ54wJJ8mV70xRiUm/UI0rJDEly1CP9erHE48seJkWBJ/xkVQJDSu5ncri/xCH9l5mvY28pslYRa2//iGcsj6BeVeyzWAh5UssTRcTsQIXuN4le8yE1JJmokorQMLo5reUtVaSgoZ8iXQ1xulIKE4HyF/TbhSJVnY5SAZ55XUr5a6or7eXqrO/XUOpNW39YeCSiZh3HG1T1CeBgaF4s+9IvrdHWlHlhdmnhYTtVQ5ni5TZBgjtLkjIxoK5pCQAt7+QpLkm4cQVFE/fgLYeUPwz87w4+Bi2RmE2zJrAe5+NdQ5QgVhTy3nYGhW3OylwWdVaBFqrjSJDgSY1qziRyDbU1LftQSo0ppS2C4OMkyRmLldyyuF5u9bHEwSeje72S9TF2+wmvIwj+TfAiC52T2p2N6nGPbYXHTehW7u5zNpZe3wtWk4JKp9NtEfcqWnYdsw7L4Wim/pthdifBaadjOxVy3kG2LtEMb2ZmRg3XmeNRhqFrPCPzD+Y0T9YjmqEjM/iK4Xonsx0bHxKCAywGwZ6caH8zRHOkhu/XyIr/a109WHamXFbc9+WljX2k5iAsHPZwjyRAa0q/2y/JVovQKi/ByhdICSj/YEkV76awrOKXR0C1L+aMacjttSUlhIzcuFtRpZqqf96ngLBNpADQneYTF+gFnVX8VCH7gxprp9KrCMArkNFOAOzCShmY5+k2/sDRCp5LYqg4FZt9XU2tl3dbNI1qHczcnnJjO/aJBLVVkO+8/Nz0WjyYkhZC25KV8JKtPvX5yVbHGzWtom5Tk6yKORgu3zEokOTdxmTQacgUc3ty6R1liamuHsJXxQi11U852PQeU72qXwwf0MklBaqOJzARuy8QqzUmzy2sKgD0oatPGBK/VwFc5QiofEQv1zdyLVNvIwhiGL34RQ9kmvoA8AluXoXjAYetXFvMpdG1K9//j2G1wcOn45ifA2+6m/FTUS+S7kK2tEpkhjJ2eamOu86350Bwh7VjvOgaZtLcR5xdqt+ledjVeUlyIWJQ+xMENxQUD/nHwxPFAcv6+9yqO28nPBI5/n7vGvADej6iUZoWnxH4Elwp1W4TamVW8y1chv6SW44FurFUU1VNrZmPAYI+T9UjG98ctXEi9/peFbIPLh7V1GtXXkW3lFAjh4VS+89tNb8oGQTAhOzHz7aPmRWxI4iGTxc1AFQQDB5F/I+zGf8C9/NbaTwQET8AAAAASUVORK5CYII=
openapi: 3.0.2
paths:
  tmp0:
    post:
      description: Swimlane Plugin with general malware detection tools.
      parameters:
      - description: Either a file or a string containing a YARA Rule
        example: 'rule foo: bar {strings: $a = "lmn" condition: $a}'
        in: query
        name: Yara Rule
        required: true
        schema: {type: string}
      - description: File or sting of suspicious data.
        example: ''
        in: query
        name: Suspicious Data
        required: true
        schema: {type: string}
      responses:
        '200':
          content:
            application/json:
              schema: {$ref: '#/components/schemas/tmp0'}
          description: Successful request
      summary: Swimlane Malware Detection YARA Scan
tags:
- {name: Investigation}
