components:
  schemas:
    tmp0:
      properties:
        job_id: {type: string}
        query_ids: {type: string}
      type: object
    tmp1:
      properties:
        alert_id: {type: string}
        device_group_id: {type: string}
        device_id: {type: string}
        device_name: {type: string}
        device_policy_id: {type: string}
        document_quid: {type: string}
        enriched: {type: string}
        enriched_event_type: {type: string}
        event_type: {type: string}
        legacy: {type: string}
        org_id: {type: string}
        parent_pid: {type: string}
        parent_quid: {type: string}
        process_guid: {type: string}
        process_hash: {type: string}
        process_name: {type: string}
        process_pid: {type: string}
        process_username: {type: string}
      type: object
    tmp2:
      properties:
        Parent GUID: {type: string}
        backend_timestamp: {type: string}
        data: {type: string}
        device_id: {type: string}
        device_name: {type: string}
        device_policy_id: {type: string}
        device_timestamp: {type: string}
        document_guid: {type: string}
        end_time: {type: string}
        enriched: {type: string}
        enriched_event_type: {type: string}
        event_description: {type: string}
        event_id: {type: string}
        event_type: {type: string}
        facet_fields: {type: string}
        facet_intervals: {type: string}
        facet_queries: {type: string}
        facet_ranges: {type: string}
        header_num_found: {type: string}
        ingress_time: {type: string}
        legacy: {type: string}
        num_available: {type: string}
        org_id: {type: string}
        parent_pid: {type: string}
        process_guid: {type: string}
        process_hash: {type: string}
        process_name: {type: string}
        process_pid: {type: string}
        process_username: {type: string}
        query_id: {type: string}
        searchers_meta: {type: string}
        start_time: {type: string}
      type: object
    tmp3:
      properties:
        children: {type: string}
        parent__s3_location: {type: string}
        parent_backend_timestamp: {type: string}
        parent_childproc_count: {type: string}
        parent_crossproc_count: {type: string}
        parent_device_external_ip: {type: string}
        parent_device_group: {type: string}
        parent_device_group_id: {type: string}
        parent_device_id: {type: string}
        parent_device_internal_ip: {type: string}
        parent_device_name: {type: string}
        parent_device_os: {type: string}
        parent_device_policy: {type: string}
        parent_device_policy_id: {type: string}
        parent_device_timestamp: {type: string}
        parent_filemod_count: {type: string}
        parent_has_children: {type: string}
        parent_hits: {type: string}
        parent_index_class: {type: string}
        parent_ingress_time: {type: string}
        parent_modload_count: {type: string}
        parent_netconn_count: {type: string}
        parent_org_id: {type: string}
        parent_parent_guid: {type: string}
        parent_parent_hash: {type: string}
        parent_parent_name: {type: string}
        parent_parent_pid: {type: string}
        parent_partition_id: {type: string}
        parent_process_cmdline: {type: string}
        parent_process_effective_reputation: {type: string}
        parent_process_guid: {type: string}
        parent_process_hash: {type: string}
        parent_process_name: {type: string}
        parent_process_pid: {type: string}
        parent_process_reputation: {type: string}
        parent_process_start_time: {type: string}
        parent_process_username: {type: string}
        parent_regmod_count: {type: string}
        parent_scriptload_count: {type: string}
        parent_watchlist_hit: {type: string}
        process__s3_location: {type: string}
        process_backend_timestamp: {type: string}
        process_childproc_count: {type: string}
        process_crossproc_count: {type: string}
        process_device_external_ip: {type: string}
        process_device_group: {type: string}
        process_device_group_id: {type: string}
        process_device_id: {type: string}
        process_device_internal_ip: {type: string}
        process_device_name: {type: string}
        process_device_os: {type: string}
        process_device_policy: {type: string}
        process_device_policy_id: {type: string}
        process_device_timestamp: {type: string}
        process_filemod_count: {type: string}
        process_has_children: {type: string}
        process_hits: {type: string}
        process_index_class: {type: string}
        process_ingress_time: {type: string}
        process_modload_count: {type: string}
        process_netconn_count: {type: string}
        process_org_id: {type: string}
        process_parent_guid: {type: string}
        process_parent_hash: {type: string}
        process_parent_name: {type: string}
        process_parent_pid: {type: string}
        process_partition_id: {type: string}
        process_process_cmdline: {type: string}
        process_process_effective_reputation: {type: string}
        process_process_guid: {type: string}
        process_process_hash: {type: string}
        process_process_name: {type: string}
        process_process_pid: {type: string}
        process_process_reputation: {type: string}
        process_process_start_time: {type: string}
        process_process_terminated: {type: string}
        process_process_username: {type: string}
        process_regmod_count: {type: string}
        process_scriptload_count: {type: string}
        siblings__s3_location: {type: string}
        siblings_backend_timestamp: {type: string}
        siblings_childproc_count: {type: string}
        siblings_crossproc_count: {type: string}
        siblings_device_external_ip: {type: string}
        siblings_device_group: {type: string}
        siblings_device_group_id: {type: string}
        siblings_device_id: {type: string}
        siblings_device_internal_ip: {type: string}
        siblings_device_name: {type: string}
        siblings_device_os: {type: string}
        siblings_device_policy: {type: string}
        siblings_device_policy_id: {type: string}
        siblings_device_timestamp: {type: string}
        siblings_filemod_count: {type: string}
        siblings_has_children: {type: string}
        siblings_hits: {type: string}
        siblings_index_class: {type: string}
        siblings_ingress_time: {type: string}
        siblings_modload_count: {type: string}
        siblings_netconn_count: {type: string}
        siblings_org_id: {type: string}
        siblings_parent_guid: {type: string}
        siblings_parent_hash: {type: string}
        siblings_parent_name: {type: string}
        siblings_parent_pid: {type: string}
        siblings_partition_id: {type: string}
        siblings_process_cmdline: {type: string}
        siblings_process_effective_reputation: {type: string}
        siblings_process_guid: {type: string}
        siblings_process_hash: {type: string}
        siblings_process_name: {type: string}
        siblings_process_pid: {type: string}
        siblings_process_reputation: {type: string}
        siblings_process_start_time: {type: string}
        siblings_process_terminated: {type: string}
        siblings_process_username: {type: string}
        siblings_regmod_count: {type: string}
        siblings_scriptload_count: {type: string}
      type: object
    tmp4:
      properties:
        _s3_location: {type: string}
        backend_timestamp: {type: string}
        childproc_count: {type: string}
        children: {type: string}
        crossproc_count: {type: string}
        device_external_ip: {type: string}
        device_group: {type: string}
        device_group_id: {type: string}
        device_id: {type: string}
        device_internal_ip: {type: string}
        device_name: {type: string}
        device_os: {type: string}
        device_policy: {type: string}
        device_policy_id: {type: string}
        device_timestamp: {type: string}
        filemod_count: {type: string}
        has_children: {type: string}
        hits: {type: string}
        index_class: {type: string}
        ingress_time: {type: string}
        modload_count: {type: string}
        netconn_count: {type: string}
        org_id: {type: string}
        parent_guid: {type: string}
        parent_hash: {type: string}
        parent_name: {type: string}
        parent_pid: {type: string}
        partition_id: {type: string}
        process_cmdline: {type: string}
        process_effective_reputation: {type: string}
        process_guid: {type: string}
        process_hash: {type: string}
        process_name: {type: string}
        process_pid: {type: string}
        process_reputation: {type: string}
        process_start_time: {type: string}
        process_username: {type: string}
        regmod_count: {type: string}
        scriptload_count: {type: string}
        watchlist_hit: {type: string}
      type: object
  securitySchemes: {}
info:
  contact: {email: frikky@shuffler.io, name: '@frikkylikeme', url: 'https://twitter.com/frikkylikeme'}
  description: Automated generation of Vmware Carbon Black Enterprise EDR
  title: Vmware Carbon Black Enterprise EDR
  version: 1.0.0
  x-logo: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAJYAAABkCAYAAABkW8nwAAANQUlEQVR4nO2de3RV1Z2Av98Bzb10zSLJ6pKE1SEJs5aATmlC62gYNTwsT9FQaFftrKmKvBTtSJUl5EnITUDsYKeoqCgUrKN9II+2omMTgw8ey5oQZhyoaxa5oWvIDZ0hF/8oCZWz549z7sm9JECnyx1u2t/3D2Gfc/be9+zv/PY+5+x9rzAAGGPMQJSj/HGIiNguw7FdgPKXiYqlWEHFUqygYilWULEUK6hYihVULMUKKpZiBRVLsYKKpVhBxVKsoGIpVlCxFCuoWIoVVCzFCiqWYgUVS7GCiqVYQcVSrKBiKVZQsRQrqFiKFVQsxQoqlmIFFUuxgoqlWEHFUqygYilWULEUK6hYihVULMUKKpZiBRVLsYKKpVhBxVKsMPRKV+D/gzEGEaF27Xq6u7upq6lKSQcwQOXq2iB9xXeXkzn8r9i8dTvRaBSArxRN4M47ZnG49d/ZsWs3GAExQX5PP/MsoVCI+xbck1L+0888j+M43L90YUq5z2x6joyMMPct+DZd8U/YvGUrZ86cQUSYeOPfMWvm9CCP5pZWjDF8eUIhLYeP8Npru1i16jGGhTMwwM6du/mw5QgOhrKylYRDVwPw+t43iUajPHD/EsAl3WPCoBIrIc/Z7h7ECE88+QNWLP8Oyd/VWrm6FoxgjMFgWL/h+xhjcAQwgojwwYfNfHTsKN3d3X7GBuNCZU2E2uoKTsZ+12/5J2OdXlkGkN76/Hfn7zDG0NzSys927UEMiDgY17D/4Accbz/Bg0sXYYyhpaUV1z/2Z7v2gIF4PM6w8AgqqmpBvMxdhMjadRQVFTG/dA5Tpkxh//6DftHpLRUMMrESCAYRhzPxTzjddYbsrOEAbNz0PMYFMOTkjqAj1okYcBwhlBEmKzuTjpMxRITusz0YA0UTimhpPoyIF4HKq9ew7P4lPL3p+aC8RGQyxngNn/Sdw8avT8WqxwiHrmZC0ZdS6mqMoaKmjqee3cyDSxcBEI1Giba1U7+mMtivvKqWmyfeyMwZ04K0tugJXtiyjfmlc2hra8OY837R6R+x0rt2/WCMYX7pHIwxuLhs2vScv8Ul1nnKv+LhofsX4yQZULHqUZYtWciEwi96EQqXyrIVzC+dQ53fwJ6UMDJ3hBfZWo4AXnTZsfsXhIeFMAiv730L1/+C8YMHDuG6btBlXfjN4yICruFkR8yrs3gRZ+rkW4N99h/4NUZIkQqgIH9UUPa4Mdcydcokf0v6N9ugi1giQmFhIb9881d0n+3hbM85f4vjN6qwaMHdgBs0cl5eHuA1+oQJE2huPYIxhlAolJKvF5G8Rvta6Rx27NrFDUXjAWhubqaupoqenh5q6tcza+ZXAfj5G//GogX3Ai5nuz8lUv84eKUzRBxcDI4I4CIiQTlTJpcEkXDv3r0ghsa338WLRr3k5+fT0nyYeXfebuN0WmPQiQWeBI8sf4hI3RMYMZztPsePXnkVMd44vCB/VLDfhcf191sGxpjedD8UFRWOZ8fOPXTFPyEWiwXCZWRchYjwn0d/Q1ZWFiJCft5fA0LdusdBDI88/E9kZw3HGOiIdfL0pucxSWWHQqGUGw5PJaHh7aYg4vZWThiZM+KzOG0DyqAUCyCc4XU9AtSufTwYd30udFXqmAj6DLi9Lk8SSX0ETJbvexv+5YJtAsbl5Vd/HKR5ZQFGqKvpHTchXreKGMS/cXBdlxy/q01w/bhr+Y9jHwddclAWKcO5QUX6d9YXxeFvCkYhODhIcKf03eXL+0qVRLJ0ycEr6Kak9/9Z2ZneMbjMnjkjSL+5+CbvzhPh+rHj/HSCY4M8DYALMjSIRP392sjc0lLEQEfs1AXHn+fcuU8ZjL8XM2gjFsCCe++mvHoNgoMR+ErheEL+IDp5POO6veOWRLcnIt4jiKR0AMfpbfxHH36IiuoIIg4Ti28I9p05YxrvHzwExvCtu76elIlLeVUts2dOIzc3l4amfUTb2kn00Rf7SaFwOIOKsse88ZkYppTcCjg0vvMOuIbaNRXIIItdgzhieTy6/GHAE6P0zjkp2xISzZs3L0grKMjrN5/c3NzgxqA3A8jIyKDwS0UkwkZCjpEjcsjJyUnKwSVSU0U4HOb1N95i89ZtRNvaWfbAQm8QJZ7MoVCI7OzsPuWHQ1fzD3d9A4zw9r73aGzaB8blkeXfwRmEMWtALoMr+etfF+sSL7ftT6fvM6aUNwNJf18p9Ne/PiOSG9XDDdJ7x1v9u3+5a6LvdqdPfsnteKWlGij+7COWX/6ANmg6RKVLoRHrM2KgGzmdpRoo/iLEUgYeFUuxgoqlWEHFUqygYilWSJtXOolb9I7YKW+mggizp09j3Lgxf/Lb2LboCTZv3UZ90ovhyz0KMMZ4r0+kn/SLvHdM5sPmI8TjcSDxcvo81113Hbk5n/eOwaHCfw0VqalIycebtvPHvbwx4M04BerWVPbmQXq8uE4bsbp7/kDt2sdxBP9dGbz06o+BIdTXlKfsm9wQF5PEayS336kzl+Ji2/tL7y+tufUw0WiU0Xn5QR0bm94FPAEE/Dn2ffP5LB5TpINUkEZiRdauQ4DI6qpAmEmTb6W+bl2fxRLR9t+Sm5tLKOMq/2gX4/fqArS1tXvvBI3/FNzfKxo9QX7+qH5P/u/P9tDZ2RnM5epP2rboCcCb73UxqRPPgu9b8O0g7XhbOy9u3d67j0BiakXvRQLR9hPk5F5DOCOUkl8iEkWjJ8jLG5Xy8jylbP/fdJArLcT63vc3Yuidy5RoMAehonxVsF959RpEhLy8vGDWgLeyxmHLlu38vruHjs4Yw8IhyleuCI5LLFIIhUL0dJ8jIyODirIVCH6krFsHYsjKyqLrdBzEEPFX7DQ0NtGw710EQ0FBAW3HowDU1lT224CC0yucAcSlLTHDIbHPBdN1yqprEePNFo1Go4gDkdXlYBxIbMeQk5NDZ+wULob6msrE4qIgn3L/c9bVVF3xp/9pIZbXmHhX8SVORmJ5VuJFb/nqCCc7Or3JdEAsFuPrc++gsHB8EBFEhOvHjuGub85HRDjbfY7IuvUcO/Yx48ZeS239Wkbm5LDsgcUkIl9FVS0v/vAlFt7zj0F3Vlm2knBoKMYIFdURdu7cxbyvlfapo4O34qcisVoIF4xQUDAaCKqV1JWbpDGg6+dfT0fsf8jNuYbK1bUMC4coe2xFn0jlHe/9veHJjb6QVUH+V5K0EMsL9Ze/wp548gfE43FcQ7BQ4ujR3zAydwSO41AwOp+ipFUynqvGl8pgEG/Rg2v40SuvsvDee8AIyx5Y7DeSg+CSlZ3J8bYo+Mc7AuHQUMBBxAUxnD7zSb91NI6AnCeyejWJC+CpZ58L1jQGwSyIKMKGJzdy+kwc4/q36Y5w9OhRQqEQroGKlStISJd8jhzHQQxUVEcwYqhbXXnFI1VQtytdAYAcP+Jc6k11W1sbXfEzFBcXs3jBPcyeOc3rCsQEk/nE7T8H70T7Kvq7DEHo6urqZ+DskD0805ublzKtxlsY4cUkwXGcYHsKRhAZEuQF8ODSJRhcGhqb+n6u6An+tytOcXExCxfczfRZM/zVPE5wd5mcVzKuex4XfyaFm/xZLz8rwzZpIdaDSxchmGAFcwJjvHEVwAs/fInbJt3K7TOmUpD/BSYW3+iPL7wxTWIRaMrx/r9Hj33cO1HPn0JcUnJLEN32HziUctzx9iihcIafr4N73p9dSu/Yj/N97zgBXHM+pVGTbx6CRheCwdHWrduYPGUSs6ffRkH+KG6+6QZwDUMwFOR7A/WX//UnJFb5eGXg18OLWJE1lfztdWOorIn0KetKkRZdIUCkpoqKqlrKq9fw9zfdCMD+gx9g8BZCTJ1UQkPTPnJycsjMzGTLtu1+BPEu1aHi8Klx++QrAi+/8hPGjhvD6LxR/PKNNwEJ1uiV3jGHXXt+zoEDh5g8uYTXdu9J6n68yNbfJL3LPZZ4ccv24O/j0XYMwuTJJd4+9N4RlpTcQkNjIyNHXENmZiYvbt2Okd5ouGzJYjY++wL/vOEpZs2awY5du71FsCtX+EMIFwHu+uY3KKuupb5+PWWrVlyyjgNB2s3Hisfj/HTnHgDmzp3L5zM/RyKwHj32Me8fPMTIEdcwa+Z0GhqbGD16NAX5o2huaQUcJhR9McjrdLyLltaPmFoykZbmj/h1awvXjx3HxOIvc2Gw/sUbb3GqI0Zh4Xg/Dye4xf+vtihf9ReYGmNoaHqf7MzhKWUlSH5A6go4xvXr+AUSkwAb9r2HY2DK5FuCz/XegYPk5o7g9hnTaWh8h9Gj84NHH+Ddnba3/5axY6/15987/Krp3SAfYwzdPX/g/YOHuG3SLZc8xwMxHyvtxFLsoxP9lEGLiqVYQcVSrKBiKVZQsRQrqFiKFVQsxQoqlmIFFUuxgoqlWEHFUqygYilWULEUK6hYihVULMUKKpZiBRVLsYKKpVhBxVKsoGIpVlCxFCuoWIoVVCzFCiqWYgUVS7GCiqVYQcVSrKBiKVZQsRQrqFiKFVQsxQoqlmIFFUuxgoqlWOH/AMeiWBKnR7SmAAAAAElFTkSuQmCC
openapi: 3.0.2
paths:
  tmp0:
    post:
      description: 'Conduct an asynchronous process search. '
      parameters:
      - description: Query string for filtering processes. Options can be found at
          https://developer.carbonblack.com/resources/query_overview.pdf
        example: process_name:svchost.exe
        in: query
        name: Query String
        required: false
        schema: {type: string}
      - description: v2, select True and for v1 select False (defaults to v1)
        example: 'True'
        in: query
        name: Version
        required: false
        schema: {type: boolean}
      - description: The field targeted (defaults to process_username)
        example: process_username
        in: query
        name: Field
        required: false
        schema: {type: string}
      - description: Max rows examined (defaults to 100)
        example: '100'
        in: query
        name: Rows
        required: false
        schema: {type: string}
      - description: Sort Field (defaults to device_timestamp)
        example: device_timestamp
        in: query
        name: Sort Field
        required: false
        schema: {type: string}
      - description: Sort Order (defaults to DESC)
        example: DESC
        in: query
        name: Sort Order
        required: false
        schema: {type: string}
      - description: The end time of the search (defaults to today's date)
        example: '2020-01-27T18:34:04Z'
        in: query
        name: End Time
        required: false
        schema: {type: string}
      - description: The start time of the search (defaults to ten days prior from
          today's date)
        example: '2020-01-18T18:34:04Z'
        in: query
        name: Start Time
        required: false
        schema: {type: string}
      responses:
        '200':
          content:
            application/json:
              schema: {$ref: '#/components/schemas/tmp0'}
          description: Successful request
      summary: Vmware Carbon Black Enterprise EDR Asynchronous Process Search
  tmp1:
    post:
      description: 'Get events associated with a given process. '
      parameters:
      - description: Limit the number of events returned
        example: '50'
        in: body
        name: Limit
        required: false
        schema: {type: string}
      - description: Job Identification of the process, required if you set version
          input to True
        example: 02855a95-e14a-4715-a6c1-586d818b9b60
        in: query
        name: Job ID
        required: true
        schema: {type: string}
      responses:
        '200':
          content:
            application/json:
              schema: {$ref: '#/components/schemas/tmp1'}
          description: Successful request
      summary: Vmware Carbon Black Enterprise EDR Get Events
  tmp2:
    post:
      description: Get the process results.
      parameters:
      - description: Query/Job Identification of the process
        example: 02855a95-e14a-4715-a6c1-586d818b9b60
        in: query
        name: Query ID/Job ID
        required: true
        schema: {type: string}
      - description: v2, select True and for v1 select False (defaults to v1)
        example: 'True'
        in: query
        name: Version
        required: false
        schema: {type: boolean}
      responses:
        '200':
          content:
            application/json:
              schema: {$ref: '#/components/schemas/tmp2'}
          description: Successful request
      summary: Vmware Carbon Black Enterprise EDR Get Process Results
  tmp3:
    post:
      description: Return organization-specific information about the process
      parameters:
      - description: The GUID of the process summary targeted to return.
        example: 7DESJ9GN-0033b832-00003c38-00000000-1d616dc047d7551
        in: query
        name: Process GUID
        required: true
        schema: {type: string}
      responses:
        '200':
          content:
            application/json:
              schema: {$ref: '#/components/schemas/tmp3'}
          description: Successful request
      summary: Vmware Carbon Black Enterprise EDR Process Summary
  tmp4:
    post:
      description: Return a tree of children (and possibly siblings) associated with
        the process
      parameters:
      - description: The GUID of the process tree targeted to return.
        example: 7DESJ9GN-0033b832-00003c38-00000000-1d616dc047d7551
        in: query
        name: Process GUID
        required: true
        schema: {type: string}
      responses:
        '200':
          content:
            application/json:
              schema: {$ref: '#/components/schemas/tmp4'}
          description: Successful request
      summary: Vmware Carbon Black Enterprise EDR Process Tree
tags:
- {name: Endpoint Security & Management}
