components:
  schemas:
    tmp0:
      properties:
        query: {type: string}
      type: object
    tmp1:
      properties:
        rule: {type: string}
      type: object
  securitySchemes: {}
info:
  contact: {email: frikky@shuffler.io, name: '@frikkylikeme', url: 'https://twitter.com/frikkylikeme'}
  description: Automated generation of Neo23x0 Sigma
  title: Neo23x0 Sigma
  version: 1.0.0
  x-logo: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAFYAAABWCAIAAADaNPagAAADk0lEQVR4nO2ZP0gbURzHf6at9ihV2sTBtgeWUAIqFCLYrQgFH13ETqWTS3Aw1EFaiGuHZihkkWTKYIYG6nRk8m3+o7SURmyLxkEavLZDtYq2NmjVOBw+znsvL3c5MVz5fcjw7ne/e/n9vvd7f+4OAEEQBEEQBEEQBEEQBEEQBEEQBEEq0VAul+sdQ53x1TuA+nPRvuu4Xop/3eXtY7evPFWVswvpvLE1EG7OblR1agD4fj9wJjGdM1UkuDG74ag7H8A3rwkhmwuc5g8ARzVdVV8qSuAmE2+pIJbAfQ4eUkEgwVlFr855QwUHi6IP4E3H1fC1RuVCg9wzU9wdWysdemTPZV0R+BL44XyGZ514YqWUrQi5ruYa8jcjqYNkMkkI0XVd3kM8HieEUErdhFGFsom2mXX2K7vA3M/42l/L2UKhMDExwV/V19fH2vl83nwo8TQTi8V449TUlDxacRW4ufkfN/fNhy+5PfXIyMjg4KC8k8nJSfmdJ4RYLMlkMh6P825Vi0gwHQrzl88Rz7/svD6duRtqq/xcLheNRoWnEokELxnDWgVaZ7PFsrV/VHWZfNVlvUpCMBicn5+37y+EUprJZMyWdDpt8VlYWMhmswDg9/slXVkl6PE3mg93D8qd7zbtxBQJNFZ3AgCAVCrV3d1NCKkkxOjoqLyH3t5eADDSMyCEqKoKACsrK8wYi8WM5LPZrN0q4IfAnbe/5NEwXnQ4KARFUSilra2tksgY5ARmCYfDANDf3887F4tF1g4Gg3aCqecrk1AopGkar0IikTAfUkoppaw0dF1vb28HgGg0akwZuq6zUZDP541GqVRaXV3l5eORSTDzc89+Psvb/+w7MxTF8buWpaWlUChktA2xIpGIMQoAYHp62mgMDAzQ01QSQibBk8Jv+5E9WNwW2ntaLtnvxEA+F7D7DCelLhwR9qlxINjfOGh3WyRnCSGapvFGQsjw8LDwEnafASCVShFC+LVQuKym02nhBOzgMUnCnwMHj0SUUjbaK63/ht1cukNDQy4CBABQVTUSifD/KHtxVmk78One9UCTz46ny0eM80E2EDqbxGcDFewexfHrU/7GeroEoOp0aE7jWdvl/y9/cPlB7dGHrfelQ97uofzBzYpwa3bjSGT3Vv5QmwSLW/sPP+/wds8lb+BMgrn1vcfLgi2jR5M3wI/r+HEdQRAEQRAEQRAEQRAEQRAEQRAEQRApx23lLR9NeKq4AAAAAElFTkSuQmCC
openapi: 3.0.2
paths:
  tmp0:
    post:
      description: Generate a SIEM Query from a Sigma Rule
      parameters:
      - description: 'A target defined by Sigma. Options: arcsight, es-qs, es-dsl,
          kibana, xpack-watcher, elastalert, graylog, limacharlie, logpoint, grep,
          netwitness, powershell, qradar, qualys, splunk, splunkxml, sumologic, fieldlist,
          mdatp'
        example: es-qs
        in: query
        name: Target
        required: true
        schema: {type: string}
      - description: A Sigma Rule (yaml) document
        example: 'title: My Awesome Rule

          description: my awesome rule description

          ....'
        in: query
        name: Rule
        required: true
        schema: {type: string}
      - description: A Sigma configuration file name. These are built into sigmac.
        example: elk
        in: query
        name: Configuration File Name
        required: true
        schema: {type: string}
      - description: A Sigma filter.  This can be a list of or a single filter
        example: level<=1,status=stable
        in: query
        name: Filter
        required: false
        schema: {type: string}
      - description: A Sigma backed option string.  Options and switches passed to
          the backend
        example: ''
        in: query
        name: Backend Option
        required: false
        schema: {type: string}
      responses:
        '200':
          content:
            application/json:
              schema: {$ref: '#/components/schemas/tmp0'}
          description: Successful request
      summary: Swimlane Sigma Generate Query From Rule
  tmp1:
    post:
      description: Generate a generic SIEM rule using Sigma
      parameters:
      - description: A brief title for the rule that should contain what the rules
          is supposed to detect (max. 256 characters)
        example: My Awesome Detection Rule
        in: query
        name: Title
        required: true
        schema: {type: string}
      - description: Declares the status of the rule. Options are stable, test, experimental
        example: stable
        in: query
        name: Status
        required: false
        schema: {type: string}
      - description: A short description of the rule and the malicious activity that
          can be detected
        example: This rule detects ransomware malware from running on a machine
        in: query
        name: Description
        required: false
        schema: {type: string}
      - description: Creator of the rule
        example: Swimlane
        in: query
        name: Author
        required: false
        schema: {type: string}
      - description: References to the source that the rule was derived from. These
          could be blog articles, technical papers, presentations or even tweets.
        example: https://swimlane.com/blog, https://github.com/swimlane
        in: query
        name: References
        required: false
        schema: {type: string}
      - description: The log source category of this rule
        example: firewall
        in: query
        name: Category
        required: false
        schema: {type: string}
      - description: The log source product of this rule
        example: windows
        in: query
        name: Product
        required: false
        schema: {type: string}
      - description: The log source service of this rule
        example: applocker
        in: query
        name: Service
        required: false
        schema: {type: string}
      - description: The log source definition of this rule
        example: The advanced audit policy setting Object Access > Audit File Share
          must be configured for Success/Failure
        in: query
        name: Definition
        required: false
        schema: {type: string}
      - description: The lists contain strings that are applied to the full log message
          and are linked with a logical 'OR'.
        example: '[''svchost.exe'',''evil.exe'']'
        in: query
        name: Detection List
        required: false
        schema: {type: string}
      - description: Maps (or dictionaries) consist of key/value pairs, in which the
          key is a field in the log data and the value a string or integer value.
          Lists of maps are joined with a logical 'OR'. All elements of a map are
          joined with a logical 'AND'.
        example: '{''client'': {''client.domain|contains'': [''*docs.python.org*'']},
          ''client1'': {''client.registered_domain|contains'': [''*docs.python.org*'']},
          ''destination'': {''destination.domain|contains'': [''*docs.python.org*'']}}'
        in: query
        name: Detection Map
        required: false
        schema: {type: string}
      - description: The log detection condition.  This will be generated based on
          the input detection data but can be overwritten by passing a value
        example: client or destination
        in: query
        name: Condition
        required: false
        schema: {type: string}
      - description: Sigma rules should be identified by a globally unique identifier
          in the id attribute. For this purpose random generated UUIDs (version 4)
          are recommended but not mandatory
        example: f5600b423a224d7f8faa5be6bb4d6fce
        in: query
        name: ID
        required: false
        schema: {type: string}
      - description: License of the rule according the SPDX ID specification.
        example: MIT
        in: query
        name: License
        required: false
        schema: {type: string}
      - description: A list of log fields that could be interesting in further analysis
          of the event and should be displayed to the analyst.
        example: destination.ip, client.ip, source.ip
        in: query
        name: Fields
        required: false
        schema: {type: string}
      - description: A list of known false positives that may occur
        example: May trigger on X product
        in: query
        name: False Positives
        required: false
        schema: {type: string}
      - description: The level field contains one of four string values. It describes
          the criticality of a triggered rule.  Options are low, medium, high, critical
        example: critical
        in: query
        name: Level
        required: false
        schema: {type: string}
      - description: A Sigma rule can be categorised with tags.
        example: attack.t1234, swimlane.host123
        in: query
        name: Tags
        required: false
        schema: {type: string}
      - description: Value modifiers are appended after the field name with a pipe
          character | as separator and can also be chained. Options are contains,
          all, base64, base64offset, endswith, startswith, utf16le, utf16be, wide,
          utf16
        example: contains
        in: query
        name: Transformation
        required: false
        schema: {type: string}
      responses:
        '200':
          content:
            application/json:
              schema: {$ref: '#/components/schemas/tmp1'}
          description: Successful request
      summary: Swimlane Sigma Generate Sigma Rule
tags:
- {name: SIEM & Log Management}
