components:
  schemas:
    tmp0:
      properties:
        critical: {type: string}
        high: {type: string}
        hostname: {type: string}
        info: {type: string}
        low: {type: string}
        medium: {type: string}
        score: {type: string}
      type: object
    tmp1:
      properties:
        result: {type: string}
      type: object
  securitySchemes: {}
info:
  contact: {email: frikky@shuffler.io, name: '@frikkylikeme', url: 'https://twitter.com/frikkylikeme'}
  description: Automated generation of Tenable Nessus Vulnerability Scanner
  title: Tenable Nessus Vulnerability Scanner
  version: 1.0.0
  x-logo: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAJYAAABkCAYAAABkW8nwAAALu0lEQVR4nO2de2wcxR3HvzNzRiQQBYidhJdJApRHgATsu7UjHgoobWkLqFXTVi1SVagc360ToA9KXwSDgPxBQRDf2XElBFRqJWjVP4ACpUBc0cR7PhOgJLySUBIegYTySPPAdzPTP2Lf7pxfd8Q3M7d3n7/mN5m5+fr2m9m52ZlZgmrDcfcBmK5myiFIshbp+huBTmFEV8ggpgVoxWnfCbCTJi4khyDko5i+/2r0PXhQj7DwUR3GinUsApEvfuH6HB+DoRNe8t6pExVuqsNYjisLcl6BlzwXAIGz6jSIofWg7ISiPotjL4j8BqY3bEBfZ27KtYaE8BvLSbwNkMZAzmZ4yXPGLusuA/g6gM0v6rM5z4HSDkQO/hEb7t87BWpDQ7iNVdhTcbyKTPLsEj6BwEmsAYQLsKOKrLMLEJfCm/16Nf8QCK+xnPbtSs8jxWtId591GJ9I4MTjAL0DwMyiaki5CZLcDJF9CoO92cNou+IIp7EKeypJFiDd9daUt3PJ6ggO7nkIHN8BAyuihoRED3j2Ngz27gJQOPYLDeEzViy+FYSe6mfwN+D1nFH2dpvaZiJStxqQLkCOKLLW4yDkVvR3pcuqzQDhMlbUfRMUp+VjLt9EJvUl7TpabpgGkV0JItegqO+YC3C6DYxeB6/ribLr00B4jFV4+xPYioHk6YbUjKY5fjIY7Qbw9SJr7IfEwwC5tSy38TITDmM57a8DLNgzbYeXPHXc8qZxVs0BsjcB9PqiynNwMJFGjl+Owd5Pyytuaqh8YznuawDUMZSXrJy/a8k1M5Cb9igIlgCoK6qOlJuQTl1QXmGHR+VcgLFodreAwZ9CEHgbA8l55gRNEc3t54Cx5wDMwkTXSMp2pFPrtOkqgco1lpPYDJDAZKfcAS91ijlBZaK1fTZy+AcoFgKMjvp3S3tnK0VNyuhnfzvhJRvHLBs2llwzA3zapxi5dgJRDCQzZkWNZvT/ANuJtr9ckFM9pgKADffvhRRX5GOKlEE141JZxnLiL4Kyc5W8ajLVCOnuv+XTnJ9vUMm4VI6xHHcTQBflY453bR1faMAfCjAWgbPKnvm6YSrDWLHECwAW52PB30MmOclK0CpC8l+ZllCI/cZyXAlCgt39Lgz0nGhMjz38KZ8i+KFBHWNit7EcV304y8UH8JLHG1JjF1z8JhARNLUVt5RHE/YaK5bwAESVvEz3XDNiLCTTvV2J2RErDCkZEzuN5bgbQUgsH3N8WMUD9YkYzKeEvMOgjlHYZywnvgFASz6WfDcyyTnmBFmMJNfm08UtNNSGXcZyXAnQ1kDOHqR7ZhvTYzvprpcKcqzp1e0xlpP4Z0HOHnjJBiNaKpXWlYtNSxjBDmM5bh9ALlLyaqYqHZH7rWkJI5g31qEHyhfnYy7/Cy9pXlelIIPPCuk3zQlRMXsBncQzSszxMTKpeoR498qUI3GzEkfdWYaUKJgzluNKgFzqZ/BPkEkeh5qpSmMg+RGC3xkVT5oT42PGWNH439UM/gm8nuOMaAkDAoGdPbTJnBCfiNbWDu29+xjKz2LyNXg9odjyZAyRXQ5at284smLKQW+PNcpU+DQs++iMMti7H8Hb4fLlxidL9RnLcR+DYir+GbzksdraDzsC/gP7HQ3NBpUA0GWsaPzPCG7U5NgLr2cmagP1qWMo8lU/MD+A12MsSr/lB3wfMkmrlniEgpfu/cQP2DGmZIyg61bo3wIPHDUHtZ6q/ERdo4v/9E83TMsWdyRjjdLh3D+6UspfG1SizViBHip3i6Y2qw9GH/TTxOgGCz3GEvIBPyDf19JmNXJkQ7sSO3Fjk6V6jFXHblfiC+O1aYZy0NeZAwf3M2i3KSl6jLVh7TblD87Sp7W0W41QEtwKFh23XLllaGzJ8wM7d++GAlq31rQEQKexpPylH4xxakqNqaH/ngOmJQA6jTWQKlx6XEMHjttmollzPUdrx5nG2g4/+wPpThMCNBuL78sns7JPb9tVBCFXBaK5JlY7aDYW+X0+yVDb1lUu+rvUJd876y/ULUGvsYi4S4mb2mrnMJQHCck/z0c5+oBuAXqN1b/uXQD+O2Uidc9pbb+aIJEf59MM83Q3b2DwLp7109y6A8NCw95ZD5tsXr+x2OfLA0FtPqtcbOkcAuC/bEDztjD9F3b0CyOtWPwfSiT8WXgitR5zZKrHeD2fao23TlCuxuEgZTKfFuQmnU2bMVYuu9RP06eMaKgGBlK78mmGGTrns8wYa7D3/YCCo1G7HephZ8P3dDVlx+DZcb9rWkJokWKbn8b9upo1Z6zgBJ7AbcZ0hB1JXT8gRwCrtVxzg8YijwVU2PtuwUpnX706CR3dvXScklOKOWNN3391ICJojS8xpiXMbOkcguDv5WMiHtfRrDlj9T14UIkFXW1ISfih7L58mhT5ss3DbVJHIxMQPEL6y8ZUhB2JK/NpzrRsFjZrLHZgjdH2q4FYx0XDrwUeYbOOZs0aq/Z4p/wQqS4Jl9nLdDRr+lao4rirTEsIDa3xJQVvopUQqMdg7x4dzZs3FueBXSXyJ+aEhIio2wpB/6XkUT53+LxSLZg3VoQEZt1JI5ratPxqCS2x9hZQbFAz2Vxs7PlQpwzzxspy9ZAwGrl4nJI1JsNJOCBso5In5PHw7vtAtxTzxhrszQJc5GNK7jSopsIh/Uoo+AvKCgeN6D01eTwk+ykI7hmOojj067B2OFuxtLgXQAZeMQcc6qkGeoyYCrChxwKA/9WnlDjWMc+MkAokmlg8ylS57AmmeqoR7DDWls4hZbUDEevNiakgnPh5oGSTkkdyJynr3Qxhh7EAAKzLT5NGczoqhOb2cwCqvq+Qi8bhLXbGscdYErVBeykw9m81Q25BpnunGTGjsesRSnCm+Fh6JJ5c+/kEpauTaGIhKHlFzczNh7fuP0b0jIM9PVYhH4llpiVYR2zl2ZVgKsA6Y/F38knJje7ktY7WjjNBhLoyQZIFNpoKsM1Ykt6QTzM2zaASu2huPwNCvqrkSbIA6a63DCmaFLuMdcruvypxNLHYjBDLYOw1JRbYarOpANuM9cgjHBz+Gi2JZyYoHX6a4wsKlr4ARJ6OgaT1h6nYZSwAYNI/2pCR6n3raqxjPhjdpuQJnIH+1FZDikrCPmN5qd+ZlmAcZ8U8ELldzRRnYyD5hhlBpWOfsQB18V9TW71BJfpxVswDIur4SdKF8LpfHbuCndhpLMoeyKdJ3a7qekVKgakgdyC9dosZLV8cu2begxQOWkfgOAgqrkK6+2mEaWlN06pGRPjbSh7n5yLT88o4NazGXmPFEmtAyC8mLMNxEAw/Qi77l0MLBiuU5vjJYHSHklfBpgJsNtYIjtsDgR8MH3c0OVx8AIalFTMmaVlxImTkHTVTLILX/bIZQVOD/cYKEkv8HIL8rIQz4jcD8lp4KW/yogZoajsekbr3lDxJFiPd9dI4NSqGyjLWCE1tdYjUXQ6OFBhOLLLWdkh5C9KpP5RVWymMHke+Dy8ZilcbV6axxqJpVSMi2RvA5YoinzNKCDwBKVYi07198uJTiLNqDsDVpcNcxJDpHtCqo4yEx1hBmtqmg9UlIPidYKyYDSMSUg4AbBnSaz8rq7axTAXZYu3t+gsSTmONYjVFdPdZAO4AJVdOWhwAIIcgsQ7phuuBTjFp8WJobZ8NwdQ9fpK3It3TP06NiqVKjFXAouuOwZFD6wF6Hor7DrIQ8gnsa1g+fDB/6YxlKoElGEhuHKdGRVOdxgpySeJoHCCPgeCS4ipwAdC7kcvdXdJumMKBuuS7ke4J7RvQasYai1jHfMjc86CsuF9oHHtBxbcxbfaz6OvMKf8WdWeBQj3hhZAL0d+lHtoRMmrGmoyo+xVQpADMR1HfFxcg7Hpksw8hUnc+gII3nMmL4KWeL4NSq6gZq3QIYu6tELgODDNKrLsUXnJ9OUTZRs1YhwdBi3stJO4CMHPCkpJchnTXsxOWCRE1Y00Zqyliu68AIbcDWJjP5uBguBFe8m5z2vTzf+rNW0qtKE3gAAAAAElFTkSuQmCC
openapi: 3.0.2
paths:
  tmp0:
    post:
      description: Launches Nessus Scan based on IP and Scan ID
      parameters:
      - description: Alternative IP targets for scan. Will scan these IPs instead
          of the scan configured ones
        example: 192.168.1.1, 192.168.0.1
        in: query
        name: Alt IP Targets
        required: false
        schema: {type: string}
      - description: The ID of the Nessus scan you want to run
        example: '6'
        in: query
        name: Scan ID
        required: true
        schema: {type: string}
      responses:
        '200':
          content:
            application/json:
              schema: {$ref: '#/components/schemas/tmp0'}
          description: Successful request
      summary: Nessus Scan
  tmp1:
    post:
      description: Stops a Nessus Scan from Scan ID
      parameters:
      - description: The ID of the Nessus scan you want to stop
        example: '6'
        in: query
        name: Scan ID
        required: true
        schema: {type: string}
      responses:
        '200':
          content:
            application/json:
              schema: {$ref: '#/components/schemas/tmp1'}
          description: Successful request
      summary: Nessus Stop Scan
tags:
- {name: Vulnerability & Patch Management}
