components:
  schemas:
    tmp0:
      properties:
        exit_code: {type: string}
        stderr: {type: string}
        stdout: {type: string}
      type: object
    tmp1:
      properties:
        files: {type: string}
      type: object
  securitySchemes: {}
info:
  contact: {email: frikky@shuffler.io, name: '@frikkylikeme', url: 'https://twitter.com/frikkylikeme'}
  description: Automated generation of Swimlane SSH
  title: Swimlane SSH
  version: 1.0.0
  x-logo: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAJYAAABkCAYAAABkW8nwAAAIuElEQVR4nO2dW0hUbRfH/9tRx7RxTN/PL53xAAlFVEgnzMjqRiSKhArCoCiKsAOBRHURBN1JRBQE0isGQQV1YWZSXkRBNxL42gEyIUybSS35xkM64zjTrO+iz75q9hz2dvZ+9sysHzww7D3PetY86z9rr30GjMcNAMRNUbuhaqY1RBLtwC8sAuAS7USckwtgTLQTgDGERaIdSED+AvAfkQ6wsBIXobFNETj2XH3AaAMBsIgaXJSwWFD6MAngjYiBRaVLFpa+6B5nvQdkQYlD11iLrLEYfcnQczA9hfUvHcdigvFAxxjomR55M2gMdIm5XhnLcKcckhhdYqFXxuJsZSw0j7uhi/fa2lrRLjAqMbSwqqurQUQIBAJobW2FJBnhDBQTDYYWlt/vBwBIkoTa2loEAgGMjY3BZrMJ9oyJhKGFRRRcmuXk5MDpdOLLly9ob28X4BUTDYYWVjjy8/Oxfft2fPr0CdnZ2aLdYf7A0MKKpqYqKirCxMQEiAiPHz/G3r17dfCMMQqqL7u12WzU0dFBgUCAlDA5OUmlpaWiLxk2aksYYjIhVquVBgYGFAmMiKixsZHMZrPoYBqpJQwxnZitW7eS0+kkv9+vSGAvX76k1NRU0UE1QksYYj45S5cupRMnTijOXjdv3hQdVCO0hEHzycrMzCSv16tIZNPT09Td3S06yCyseaDrxJWUlNDTp0+jFlhxcbHoQLOwVKL75Ckp9FlYscfQx7Hmw8TEBFavXo2hoSHRriQlCSustLQ0dHZ2orCwULQrSUlCCauiogJNTU0gIszOzmLt2rVR9Zs72c3EH5rWDOXl5XT58mVFe4SBQIA6Ojpo9+7douudhKyx9CLmk5OTk0M1NTWKxERE9PnzZ1q0aJHowIpuCUNMJsRkMtHz588Vi6m3t5fKy8tFB9NILWFQPQlms5kaGxvJ4/EoFtThw4dFB9CoLWFQNQE7duxQLCYiooaGBj7pLFhYqXoMopby8nJF31+zZg3ev38Pt9utjUNM1MT94Yb6+npIkgRJkvDPP/+wqAyCoTOWHESEXbt2oa2tDYFAQLQ7TAgMLSyfz/fzs9PpxMqVKzE+Pi7OISZqDL8pvHv3LvLz81FUVMSiYoJQtfeyb98+ysjIEL0HlYhNc/jZDcmJ5nE3dI0lApvNhvv37+t6t3VJSYluY+kFC+sPTCYTbDYbiouLRbsS1xi+eGfiExYWowksLEYTeK8wOUnuJ/ox8QsLi9EEFhajCSwsRhNYWIwmsLAYTWBhMZrAwmI0gYXFaAILi9EEFhajCSwsRhNYWIwmsLAYTWBhMZrAwmI0gYXFaAILi9EEFhajCSwsRhMS6obVhQsXIisrC3a7HRkZGXC5XPj48SNmZmZU27TZbMjMzERBQQEmJiYwPj6OwcHBGHrNzAfNHnAhSRLduXOH3r17F/LRkR6Ph3p7e6mpqYksFktUdvfv3x/25Zter5devHhBVquVJEmSteHxeMjtdv/WNm3aFHZcl8sV1M/lckXsp7AlDDEXlMlkourqalXPKH39+rWszZ07dyp+B+IcBQUFQfbk2Lx5c9jf5Xa7g/q43e6I/RQ2zYnLGuvSpUvw+/3o7OyMmc3r16/jwYMHMJlMqvpH8/7qZCIuhXX69Omw66empjA8PIypqamobR47dizs+tHRUbjdbnz//j1qm8lM3Anr2rVrIdfNPeTWYrGgsLAQFosFkiQhPT0dBw4cCFnENzc3yy6vqan5aTM/Px9ZWVlITU2FJEnIyMhAd3d3TH5TIhJ3wqqsrJRdPjIyErKPz+fDrVu3UFdXJ7t+/fr1ssvDbWq9Xi+2bdsWxtPkJu4ON6xatUp2+fT0dMS+ra2tsrXQ8uXLVfny9etXrq1CEHfCGhwcRFlZWdDyJUuWYHR0FB8+fMDx48fhcDgwOjoalU2Hw4HS0tKg5USE7u5u9Pb24syZMxgeHp6v+xFfipCSEncbEaHEbFf5yZMnEXf9XS4XvXnzhvbs2UMpKSkRbT579iyizb6+Pjp48CCtWLEial/lmJmZCTq29WuTIx4PN+hFTI9hqWVgYCCk0NQQCATIZDLF3M8/iUdhxWXeVftG1JKSEpw9e1Z2nZq3XEiShIsXLyIvL0+VP8z8iWnGAkAnT54kh8OhKgOcO3dO1ubIyIjqrJKens4ZSwAxF9avraqqis6fP68oWJFsFhYW0tjYmCKbf54zlCNZTunohabCAn6cjL5y5Qp1dXWRz+eLKAKr1RrR5rp16+jVq1c0NDQUlbByc3NZWDqjubDkWlpaWsiTyhUVFYrtmc1mqqioCCmsqqoqFtb/iLviXcm1UD6fD8uWLZNd5/V6f352OBxR2fN6vejq6gq5fnZ2NmrfEp24E1ZxcTGICD09PTh69GjE709OTsouf/v27c/PdrsdRISGhoZ5HUnv6elR3ZdRR8zSuBwPHz6kCxcukNVqpaysLLJYLGS32+nevXshN1uRbPb391NZWRllZ2fTggULqLS0lNrb28npdMp+v6mpKSpfk2VTqBeaCksphw4dirlNuatI5UgWYcXdpnC+XL16FS0tLTGz19zcjMWLF4MooRJB3HADMfq39fX1qc4qjx49krXZ39+vyp7X61WcXQ2QsW7GMK4h0fOaj5j+pdPS0pCXl4fbt2+jsrISZrM5qPCenZ1FS0sLTp06FdUem91ux5YtW7BhwwbU1dUhJyfnt/V+vx/fvn3Dxo0bMTAwAI/HE9ZefX190LK2tjYMDQ2F7HPkyBGkpv5+0Ynf70dHR0fYfgrQJeZ6CuvfAEJfjcfowWIAX/QYSO+r1LgQEUcmgPApNoboXbz/pfN4zP/RTVSA/hlrDs5c+qJ7nEUdbrAKGjcZEZI8RAlrEgDfO6U9wu70MMItJrxZ1AahsTXCkXcJwALRTiQQC2CAhGEEYQHADIBc0U4kALn4MZfCMYqwAGAMP/5pf4t2JA75Gz/mbky0I3P8F8vC1N9uvkeDAAAAAElFTkSuQmCC
openapi: 3.0.2
paths:
  tmp0:
    post:
      description: Runs a command on an SSH server.
      parameters:
      - description: The command sent to the ssh server
        example: echo Hello World
        in: query
        name: Command
        required: true
        schema: {type: string}
      responses:
        '200':
          content:
            application/json:
              schema: {$ref: '#/components/schemas/tmp0'}
          description: Successful request
      summary: SSH Run Command
  tmp1:
    post:
      description: Get a file or folder on an SSH server.
      parameters:
      - description: Name of the file or directory, must be an absolute path
        example: f.txt
        in: query
        name: Filename
        required: true
        schema: {type: string}
      - description: Optional limit of files to return. Defaults to 100
        example: '50'
        in: body
        name: File Limit
        required: false
        schema: {type: string}
      - description: If True, files in subdirectories will be returned. Defaults to
          True
        example: ''
        in: query
        name: Recursive
        required: false
        schema: {type: boolean}
      - description: Regex for matching filename. Defaults to match any
        example: ^.*\.(xml|PDF)$
        in: query
        name: Regex Pattern
        required: false
        schema: {type: string}
      - description: Delete the file on the remote host after copying it locally
        example: ''
        in: query
        name: Delete after Copy
        required: true
        schema: {type: boolean}
      - description: Defaults to True. If False, will include all attachments in one
          record
        example: ''
        in: query
        name: One Attachment Per Record
        required: true
        schema: {type: boolean}
      responses:
        '200':
          content:
            application/json:
              schema: {$ref: '#/components/schemas/tmp1'}
          description: Successful request
      summary: SSH SCP Get File/Folder
tags:
- {name: Miscellaneous}
