components:
  schemas:
    tmp0:
      properties:
        success: {type: string}
      type: object
    tmp1:
      properties:
        success: {type: string}
      type: object
    tmp2:
      properties:
        EPOBranchNode_AutoID: {type: string}
        EPOComputerProperties_CPUSerialNum: {type: string}
        EPOComputerProperties_CPUSpeed: {type: string}
        EPOComputerProperties_CPUType: {type: string}
        EPOComputerProperties_ComputerName: {type: string}
        EPOComputerProperties_DefaultLangID: {type: string}
        EPOComputerProperties_Description: {type: string}
        EPOComputerProperties_DomainName: {type: string}
        EPOComputerProperties_FreeDiskSpace: {type: string}
        EPOComputerProperties_FreeMemory: {type: string}
        EPOComputerProperties_IPAddress: {type: string}
        EPOComputerProperties_IPHostName: {type: string}
        EPOComputerProperties_IPSubnet: {type: string}
        EPOComputerProperties_IPSubnetMask: {type: string}
        EPOComputerProperties_IPV4x: {type: string}
        EPOComputerProperties_IPV6: {type: string}
        EPOComputerProperties_IPXAddress: {type: string}
        EPOComputerProperties_IsPortable: {type: string}
        EPOComputerProperties_LastAgentHandler: {type: string}
        EPOComputerProperties_NetAddress: {type: string}
        EPOComputerProperties_NumOfCPU: {type: string}
        EPOComputerProperties_OSBitMode: {type: string}
        EPOComputerProperties_OSBuildNum: {type: string}
        EPOComputerProperties_OSOEMID: {type: string}
        EPOComputerProperties_OSPlatform: {type: string}
        EPOComputerProperties_OSServicePackVer: {type: string}
        EPOComputerProperties_OSType: {type: string}
        EPOComputerProperties_OSVersion: {type: string}
        EPOComputerProperties_ParentID: {type: string}
        EPOComputerProperties_SubnetAddress: {type: string}
        EPOComputerProperties_SubnetMask: {type: string}
        EPOComputerProperties_SystemDescription: {type: string}
        EPOComputerProperties_SysvolFreeSpace: {type: string}
        EPOComputerProperties_SysvolTotalSpace: {type: string}
        EPOComputerProperties_TimeZone: {type: string}
        EPOComputerProperties_TotalDiskSpace: {type: string}
        EPOComputerProperties_TotalPhysicalMemory: {type: string}
        EPOComputerProperties_UserName: {type: string}
        EPOComputerProperties_UserProperty1: {type: string}
        EPOComputerProperties_UserProperty2: {type: string}
        EPOComputerProperties_UserProperty3: {type: string}
        EPOComputerProperties_UserProperty4: {type: string}
        EPOComputerProperties_UserProperty5: {type: string}
        EPOComputerProperties_UserProperty6: {type: string}
        EPOComputerProperties_UserProperty7: {type: string}
        EPOComputerProperties_UserProperty8: {type: string}
        EPOComputerProperties_Vdi: {type: string}
        EPOLeafNode_AgentGUID: {type: string}
        EPOLeafNode_AgentVersion: {type: string}
        EPOLeafNode_ExcludedTags: {type: string}
        EPOLeafNode_LastUpdate: {type: string}
        EPOLeafNode_ManagedState: {type: string}
        EPOLeafNode_Tags: {type: string}
        error_message: {type: string}
      type: object
    tmp3:
      properties:
        completed: {type: string}
        expired: {type: string}
        failed: {type: string}
      type: object
  securitySchemes: {}
info:
  contact: {email: frikky@shuffler.io, name: '@frikkylikeme', url: 'https://twitter.com/frikkylikeme'}
  description: Automated generation of McAfee ePolicy Orchestrator via Data Exchange
    Layer
  title: McAfee ePolicy Orchestrator via Data Exchange Layer
  version: 1.0.0
  x-logo: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAJYAAABkCAYAAABkW8nwAAAI50lEQVR4nO3de4xUVx0H8O859wFzd5eZO1DEurKPQqtNKE3ThP5Bgd3lWS3URENaXzU1aapp01rjI1EbEmO0wUf/0X9MTPqHVBqTUhFF2NluxUaNVfuwiIV9IUUscGf2cWf33rnn5x/ttnTdWXZ35sy5d+Z8/iLM7Dlfwnd+5+ZywwAKHbWd8Lidelhlhnoz7Lp7T7e0jKvOwVRunrMdeutXpUuMzK1dof93lXmSLJ9Ou54QLzPTbAWAds9T+ncbk2K9iyIaMCO2cTP88yoyJUmhpWW5x9gvYRibZ76mulhc5eazYQbrjGy8kbOcH/QBpuo8cUQAH8hkHvJM8+JspYqD2BXrHQyPkO2EOdN5VnWUOBnJZr857LoRZ+wJ1VnmErujsBwC/JBF63dOTZ2WmSmORpYty04JcdayLGe+P6OPwnligGOT8XrOSJ3KmakNqvPUwr+y2dYh1/2rMIxLCylVHCRmYs2GiE70hMXbq5UnLoYzmaeJsY9XsoaeWBVgjG3M2Q7lbOcxUvwhqYbBTOYLQ65LlZYqDhI9sWbijHVvmZroq+aatTCUzd4Ion9Uc03VE6uuijWNIF6JIPZuD4KTMtavhtNNTStN0zwEzm+Tsb4ulkwCw1HJX78NKEjdZwEIYAOue9oAOmXuo7pYib7GuiqONsN28n3W0sOqowDAkOv+eDid9mWXKg7qe2LNEAJkEX27Oyx+q1Z7DmezjwRE+60af4hVT6yGKtY7BM6BYU936L8oa4s3mpuvmbKsXgask7XHXHSxVItogEXRR7oQ/LPSpS5ms61jRAcYsLEa0Sqhulj1fY01HwbrJNs8mbNSj78K2ItdZtB1Hx0nOhuHUsWBnlgzRXRXd1Q8NN+3DzQ3b+KW1S8z0mKonli6WGWEQGko8J37gXDmawTwoebmPLOsFhXZ5kN1sfRRWIYFmGttJzhupN5zk3UonT457LpRnEsVB/pBuqvgBvtQznAozfmR5SnrDtV5kkJPLE0KXSxNCl0sTQpdLE0KXSxNCl0sTQpdLE2K5BeLwv92Bz5jJXG36iiVEEQPt910k0VEv1CdpRqSX6y3dYnJp5YtTzdFoAOqsyyIEEfMUmlFZz7/BOvvL6mOUy11def91vPnfQD3ALjnMJxVKYOeZwZbqzrXTEyI8wDubCsUpD0PplrdTKyZPgr/Pz1R8foowp0AItV5pjEhPtdWKFxbz6UC6mxizWZb5B9G9Nafs9d2vsyA76GGH6gQIAv4TrvnfaNWe8ZB3U6s2fQE/v7uwDdI4Fe12E8I8cJaz+ONViqgASbWbHpK/m4CWJ/p/Bsc11Z7/RC4XPC8VbfO8ixXo2jIYgEAAwgl/wMAcHTJkg6LjIFK1xREN3fm8y9Vni75GuooLGfH1NRgV+BzAfpYCCz4qVYS4r42zzN0qd7VsBNrJgYQguIzePvD1mulvs8Y+1K590dCPOUVCp9p5ONuLnpildETFh9lgd8iiHqv/H0CXuKMtV5XKNytS1WeLtYcuoDxrWFxKxPidpOzUTD2+Q7Pu3n15cvnVGeLO30UzkNXafIESpMn4KtOkhx6YmlS6GJpUuhiaVLoYmlS6GJpUuhiaVLoYmlS6GJpUuhiaVLoYmlS6GJpUuhiaVLoYmlS6GJpUuhiaVLoYmlS6GJpUuhiaVLoYmlS6GJpUuhiaVLoYmlS6GJpUuhiaVLoYmlS6GJpUuhiaVIkvlghs1qOomml6hzVMAKkwNiNqnNUQ+KLZQEpy6YLvzOds6T4q4gXiwB2Jp1+Qbiuz4B1qvNUQ11+J7TgYtPWycnfy1i7mobS6VuI8z8xCf/rj/5OaAm44M/nbGf8mLX0k6qzzGYgk9k06LpvgvMXZZQqDupyYv0foon+sLhsHyBqst9sEQA2ksmcJsY6a7Gfnli1wFjTZtuJcqZz6C+AU8utCbAH0+knh11X1KpUcdAYxZrGsXvUdiZ67aVfRw2m9ZlM5lPDrjvFOP+07L3ipjGOwjJKVLpo21b3lomJV6q15pkVK67nUfRrBqyp1pqLofoobOhiTSsRjS3hYv3mqanBxa4xsmxZVnD+Ghh7XzWzLZbqYjXWUViGyVhLRMZAznao10rtW8jPDmUyDw65LgnDuBSXUsWBnlhlREI8u600uafc6wOZzE85Y/fVMtNC6IkVUwbnu3ttp5SznPeU51wms2eoubkQ51LFgfJ/AvktkIXtXLBjfqMwzfmR5SnrDtU55hISiWaiNe8vFBZ9rVgtyifWTuDyzsC3iPBZIhpVnSfBvro2nzfiUCogBsWa1hP6T/aExfTrgW9HEf1MdZ6EOBQwlm73PNbueY+rDnMl5UdhOc/Z9ofDyDhiGKxddRYgZkehEJME7OooFJ5THaWc2F7XbAmCkwA6+iKsINt5U3WeuCDDuKXD8/6mOsfVxLZY07qAiwh8BgB9Vuq7AWNfsWI8aWUgooMd+fxe1TkWIjbXWPPRFRa/tiPwOQj3q85SE0Q/avc8lrRSAQn/5D8DtDim+ZrJ7VbZe9XqGosBeRZF160eHb0sey+ZEjWxZroLGNteKn1QCNqAiM6ozlMRogucaEub57lJLxWQ8GJN21oq/rk7Kq4B4d6k3QsjohITYl97Pr9qdT7frzpPtST6KCyHAN5rLf0hZ/yhaq0p4Sj8+UXPu7dev1e6Lot1pWOW/UeDmRsqXadqxQrDkfbx8baK14m5ujgK57ItDG7rDnwWCrFR1XUYI8ozxna0ex5rhFIBCbiPVS07SpN/ALCm17BvAMyXGWDXYl8OrFudz79ai73ipO4n1kw9QXCqO/CXCkYPyNxHED3Gm5qc1Z7XcKUCGuAa62oOAvYKy9kPhgfnet98rrGI6KAhxAP1cLugUg1frGm/QcsNS6zJfjBr1seL5ypWGEVFg/NdnXV0u6BSDXONdTW7MHYKIVYBIXJGU4/g4QHOzGvKvT8kIlOIL3aMjv6kljmTQhdrFt3RRC8irMzZxkGAfWLm60R0bG0+v11FtqTQR+E8HLdSx13DmFpusdb2sbH1qvMkwf8AXp8TpgRO+u0AAAAASUVORK5CYII=
openapi: 3.0.2
paths:
  tmp0:
    post:
      description: Apply a tag to host
      parameters:
      - description: Comma Separated list of host names or ip addresses
        example: 1.2.3.4
        in: query
        name: System List
        required: true
        schema: {type: string}
      - description: Tag Name to apply to hosts
        example: Name Of A Tag
        in: query
        name: Tag Name
        required: true
        schema: {type: string}
      responses:
        '200':
          content:
            application/json:
              schema: {$ref: '#/components/schemas/tmp0'}
          description: Successful request
      summary: McAfee ePolicy Orchestrator DXL Apply Tag
  tmp1:
    post:
      description: Remove a tag from a host.
      parameters:
      - description: Comma Separated list of host names or ip addresses
        example: 1.2.3.4
        in: query
        name: System List
        required: true
        schema: {type: string}
      - description: Tag Name to apply to hosts
        example: Name Of A Tag
        in: query
        name: Tag Name
        required: true
        schema: {type: string}
      responses:
        '200':
          content:
            application/json:
              schema: {$ref: '#/components/schemas/tmp1'}
          description: Successful request
      summary: McAfee ePolicy Orchestrator DXL Clear Tag
  tmp2:
    post:
      description: Get Host Info from ePO
      parameters:
      - description: Host to search for
        example: 1.2.3.4
        in: query
        name: Host
        required: false
        schema: {type: string}
      responses:
        '200':
          content:
            application/json:
              schema: {$ref: '#/components/schemas/tmp2'}
          description: Successful request
      summary: McAfee ePolicy Orchestrator DXL Get Host Info
  tmp3:
    post:
      description: Wakeup ePO Agents
      parameters:
      - description: Comma separated system names to wake up
        example: system1,system2,sys
        in: query
        name: Names
        required: false
        schema: {type: string}
      - description: Comma separated IDs to wake up
        example: 1234112,2341151,3253562
        in: query
        name: IDs
        required: false
        schema: {type: string}
      - description: Group ID to wake up all systems in group
        example: '1123'
        in: query
        name: Group ID
        required: false
        schema: {type: string}
      - description: if true, full properties will be sent by Agent. Defaults to false
        example: ''
        in: query
        name: Full Props
        required: false
        schema: {type: boolean}
      - description: If True, Wake Up SuperAgents, Defaults to false
        example: ''
        in: query
        name: Wakup Super Agents
        required: false
        schema: {type: boolean}
      - description: Minutes to randomise the wakeup calls, 0 means immediate. Defaults
          to 0
        example: ''
        in: body
        name: Minutes to Randomize Wakeup Calls
        required: false
        schema: {type: string}
      - description: If true, Agent will force a full policy update, defaults to False
        example: ''
        in: query
        name: Force Full Policy Update
        required: false
        schema: {type: boolean}
      - description: "If true, uses any available Agent Handler. Defaults to false\
          \ (use the last Agent Handler that connected to client system if appropriate).\L"
        example: ''
        in: query
        name: Use All Handlers
        required: false
        schema: {type: boolean}
      - description: "Retry interval in seconds. Defaults to 60.\L"
        example: ''
        in: body
        name: Retry Interval Seconds
        required: false
        schema: {type: string}
      - description: "Retry interval in seconds. Defaults to 60.\L"
        example: ''
        in: body
        name: Retry Interval Seconds
        required: false
        schema: {type: string}
      - description: Maximum number of minutes before aborting all attempts. Defaults
          to 20.
        example: ''
        in: body
        name: Abort After X Minutes
        required: false
        schema: {type: string}
      - description: "If true, deploys to all child groups when deploying to a group\
          \ using groupId property. Defaults to false.\L\L"
        example: ''
        in: query
        name: Include Subgroups
        required: false
        schema: {type: boolean}
      responses:
        '200':
          content:
            application/json:
              schema: {$ref: '#/components/schemas/tmp3'}
          description: Successful request
      summary: McAfee ePolicy Orchestrator Wakup Agents
tags:
- {name: Endpoint Security & Management}
