components:
  schemas:
    tmp0:
      properties:
        CATEGORY: {type: string}
        CONSEQUENCE: {type: string}
        DIAGNOSIS: {type: string}
        DISCOVERY: {type: string}
        LAST_SERVICE_MODIFICATION_DATETIME: {type: string}
        PATCHABLE: {type: string}
        PCI_FLAG: {type: string}
        PUBLISHED_DATETIME: {type: string}
        QID: {type: string}
        SEVERITY_LEVEL: {type: string}
        TITLE: {type: string}
        VULN_TYPE: {type: string}
        composite_key: {type: string}
        dns: {type: string}
        fqdn: {type: string}
        ip: {type: string}
        netbios: {type: string}
        port: {type: string}
        protocol: {type: string}
        qid: {type: string}
        result: {type: string}
        ssl: {type: string}
      type: object
    tmp1:
      properties:
        DETECTIONS_FIRST_FOUND_DATETIME: {type: string}
        DETECTIONS_IS_DISABLED: {type: string}
        DETECTIONS_IS_IGNORED: {type: string}
        DETECTIONS_LAST_FOUND_DATETIME: {type: string}
        DETECTIONS_LAST_PROCESSED_DATETIME: {type: string}
        DETECTIONS_LAST_TEST_DATETIME: {type: string}
        DETECTIONS_LAST_UPDATE_DATETIME: {type: string}
        DETECTIONS_PORT: {type: string}
        DETECTIONS_PROTOCOL: {type: string}
        DETECTIONS_QID: {type: string}
        DETECTIONS_RESULTS: {type: string}
        DETECTIONS_SEVERITY: {type: string}
        DETECTIONS_SSL: {type: string}
        DETECTIONS_STATUS: {type: string}
        DETECTIONS_TIMES_FOUND: {type: string}
        DETECTIONS_TYPE: {type: string}
        DNS: {type: string}
        ID: {type: string}
        IP: {type: string}
        LAST_SCAN_DATETIME: {type: string}
        LAST_VM_SCANNED_DATE: {type: string}
        LAST_VM_SCANNED_DURATION: {type: string}
        NETBIOS: {type: string}
        OS: {type: string}
        TRACKING_METHOD: {type: string}
      type: object
    tmp2:
      properties:
        dns: {type: string}
        fqdn: {type: string}
        ip: {type: string}
        netbios: {type: string}
        port: {type: string}
        protocol: {type: string}
        qid: {type: string}
        result: {type: string}
        ssl: {type: string}
      type: object
  securitySchemes:
    BasicAuth: {scheme: basic, type: http}
info:
  contact: {email: frikky@shuffler.io, name: '@frikkylikeme', url: 'https://twitter.com/frikkylikeme'}
  description: Automated generation of Qualys Vulnerability Scanner
  title: Qualys Vulnerability Scanner
  version: 1.0.0
  x-logo: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAJYAAABkCAYAAABkW8nwAAANV0lEQVR4nO2deXSVxRnGn/mWm329ASIiSsmikJsgW0Gw0EPFI6ICeqBqEYVKKW4c1KIWRavV0lY9iEfBilWsx2oVt9pWRZEqSAWB3ISEJCDQosIhudljcr9l+gfGgxqTme9+c7/5En7/8s47T8hz505meYegj1MbyruMEDIBFp1mqtYZGvQAbw7TMAxN1w8RG5sosDFYXv2iCK1+gngtIJ4cGz5kjKro86MEC3VAEd2fAVCV0r9phKzNCle/J7o/mei1xqoN5Q0CyAPEtGZC11K81tOJYVJLVfEyoNzVr6yqyms9ouh1xoqEChZHLdyva8jwWktPGIZh6LqyMhjef6fXWtym1xirLlSwyrDodbpGVK+1OIJgQ7C0+lKvZbiFr40VCRWspQQLvdbhOrb9XrB83xSvZcSCL41VV5Q/DYr5AqCneq1FFAZAEyidn1VW87TXWpzgK2PVFRU8AwVXea0j7lBszC6rPp8AttdSWPGFseikSVqk/gvDax1eY0WVgf337v3Cax0sCF/LiZXa0NA1J011HDVgf14XKtjgtQ4WpB2x6koKJoDiQ691yAq16LycPTXrvdbxfUhprKPDTs/VtARfDPleYlNrdL+y/Z94raMrpDNWbXHefAJlnZcatOIS6Oeci8CUqVCH/ADQ9W/8u3XgU0TffQvGtm0wt2/zSGUn9OFguGapxyK+g1TGqisuoPHuU83LR+qDq6GeMSTmXPaRI2hZshhm5R4XlPERDFdL9buURszR4vxDGsjgePWnDitC+uNPgmRmuZ6bNjai9d47EX3nLddzfx+GQRtyK2vc/2EcIoWxqvPyEoLJSrvofoimI/XRtdDHTxDd1ddYhw+jadY00I4O4X0RNXpG9q6Dh4R3xIAUyw0ZAUP4J00ZkIusT8rjaioAUAcNQtbHYajDioT3RWx9pPBOGJHCWJqixT7B6YaU+1Yi8+3NIrvokYznX0b6088L7cOylWFCO+BACmMBZLqIrMqAXGSXViHhohki0nOjnT0S2aVV0ErOFpKfEsR3OO4GKYxFFeL694Q2+oeej1LfR/r6vyLpmmsFZLZOFZDUEVIYiwCuzg0S5y1A+jppF6UBAElLbkHqfStdzWkZ8furuiekMJYBMtCtXAlzrkTy0l+5lU4ogYtmIOWOFa7l03WS6VqyGJFiucHNhdHsUpeOkVOKjtdfhfnJdph7K0AbGkAyM6Hm5UMfNRqBqdNA0tJc6ap+dBGo4c4+uywLpVKIcMVYioLsXZXO21sWWpcvQ8c/3uBuqp55FtIeWg3l1NMcd98w/TzY//uv4/adyGIsKb4K3SB7Z4Xjtu3rn0Jk5DBHpgIAa28lGqb9BM1LrnOsIfPv7zhuKyO9wlgJV10NEP4Pavv6PyNSUoi2B92ZRBubNiJSUoimeZcDlH8QTln5sCs6ZECKYTPWr0In86rGWdNh7a+JpdseydqyAySVbx7WMGUC7Npax32e/Cp0iYwNb3K3qR81XLipAKB+wmjuNhmvx2/jWiS+NlbysuVQh+axN6AUkRFngpqmOFHfIlJSiOimjczxJCUVGW+8LVBRfPC1sRKvmMsVXz8m5GjuEystnJN6dfDpgpTED98ai2RkcsW3LF/m2lqRE+rHlnCZmmsklhDfGit15UPMsdahg4i+8ao4MQzQjnY0/3IBc3zaE88IVCMefxpL17nOVTVefL5AMewYH21hjlVycoBU/1709qWxEudcwRxL29oEKuGn7RH2kTZt1RqBSsTiS2Ml3XQzc2zjrAsFKuGnfd1a5lh9pDQHQrnxpbFIIIEpzqqugv3F54LV8NO8aD5boOLPikyAT43FSusD93otoUt45lp+xX/G+tbl0e4wd24XKCQ2zPBupjiSHRQrRBC+M5bSrz9TnLU3hiM0ceDLJx5jitOGDResRAy+M5Z2Ftt/dPT9dwUriQ2zrJQpTp84SbASMfjPWCPYbri0Pyf3mXfa0MAUp589SqwQQfjOWCQrmymONjUKVhIfSHq61xIc4T9j+Xg1ui/hO2PBw43kk7DjO2PZjHOT3gJtavJagiN8ZyxrL+OlCVXuVWtlINulZaNst1ghgui1xtJCxYKVxEZgJtsjFMYH/xasRAxyGIuC+e6WtX8fU1ziPPazT16QvJDtVKmxmf3RMJNaEad63EYKY9m2zVwsjLaz1WfTx090rEc0oo4ea1CPCEnsACmMpSjE9U09kpTkdkrXSHtGTJ0smxApqvkBkhiLaNpTIvImzr1aRNqYSJh5GRTWjWXOix8apdI8LiCFsRojbUd54u3PP2OKS15yqyM9Ikm5+7fMsdH3+PY7qRaV5p6+FMYacugQV2Hbpp8zXvvSNK5jzKLhrX/aspTv2pgshW0BSYwFACaMKGus/RnbiAUAybfJ83hp2hr2b3zWUbkTg3pwYbIbpDGWDp39OwJAdPMmtkBFjh8x812+Z4EaZ1/CFa+CbuVqIBg5/tcBNDZ2/J4nvuXGRcyxWVu9fW4m6drFUHL6cbWhzc1c8Zpi/IyrgWCkMRbvPIsHkpKK5GXLRaXvFn38RCRdfxNXm+hG/sIgWaWHDnI3Eog0xnJC09w5zLGJV8wFycwUJ6YLtKIQ0tbwvTdlhkvRcvONghTFD6mMZXPOE8zwbq6nRLI2/8dRgTYnBCZPQfpzL3G3a5r3U/7ObFO6O25SGYtQyj4EfQXvhdSsHeW8XXCTdP0SpK5iuyxxIi233QLY/M8+W0S9hbuRYKSo/nYiTl4B04YNR/rzHIvOtoXI2BL3Dw0qCrLe3waSkcHd1K6PoGHyeO52hgkrt6Ja424oGKlGLAAgoDN425gVnO8DKiqyd5RDOcW18vIAgOxdlY5MBUodmQoAdJXc7qihYKQbsQCgrnjoXkAt5Gqkqo4qJ3e8tgGtd8X2u0l/9gVoxSMct4+U8P2onRiAnRuulvJEo3QjFgDAwnn8bSw0LeCr8AcACZfMQtb2Mu52J9I0dw7qJ40DosybB1/TcMGPHferq5a0Z4OkHLEA55WUHb9MYdtonHEBrFiXgxQFaY/9Cfq4CT3+BVo/eRxofb3jrmSpkNwV0gqrCxXcDwJH31Hpz70ErSjkuO/mGxfBYN0yYoAEEhCYegG0cecg4cLpoE1Nx0e4mLB3BMP7xrgiUADSGguIrf57zG/qWBbqzx0D2toaWx5BPBKuVu8B+Ncm4oScc6yvME3N8StIkZJCmFUxFAZRVWRt3Yns0iqkPb4OJChT1RczJLOpAMlHLCD2VytSH1qNwJSp7oixbTRePsvzSjYyz606kXrEAgAK3B1L+5alN7hXhltRkPHCq8gurULyHSu4anW5BaXk2bh36gDpnQ8AdaH834CQ2E7sOVzn4qFp4dWwSncx3yRywMZguJp/KcYDfGEswJ03DZX+A5D51vvCD//R5mYYH29Dx+uvHL8X6NLhzuyZl6vknnuknlt14htjHSsqHK0o1JVrYvqEc5G2eg2gxn+Lza6thfHhZhgfbYGx9QPm2gzEtudml+/7i2B5ruEbYwHAsaKCJxQFrj3/nvzrFUic7d1lC3P3zuNvG/YABd2ZE67xVQU2XxkLAOqK848AZIBb+fSx45D22JOeTMRZ9ggNwzByKw8E4iDHVXxnLMDdx8k7IYEEpPzuQQSmxGFuTCkio4YDltVjqB+WFrpC+uWGrrBsZbLbOWm0Ay1Lr0ekpBDWwQNup/8G9WNCTKaygcVChQjEl58GAKCAEiku6Pm3EwMkKRnJt96OhEtnu5aT9YhMq6kFB1dUSFM9hhffGgsAakMFuwjBiHj0FbhoBlJX3Od8LhaNIjK2mG3pwcSXwYrqZGcdyYGvjQUAR4uH1mlQ2Uopu4CSnoHApbORfNPNXBczWEcqw6ANuZU1WU71yYLvjQUAR0ryZ+qUeFZpRT1tMAIXz0TilVeBpHyzqnPbw39A+9NPsiUieCBYWn2HAIlxp1cYCwDqioc0A7oUtbqVgadC/9Fk0IYGRP/1JlMbw6RWbkWNdJcinNJrjAUAtcX5swjIy17r4MUm9Df9SmtWeK3DTXqVsQDgWNGQY4qi53itgxVq0LacypoUr3W4jS/XsbqjX/mBftSyq73WwYIBWt8bTQX0QmMBQM6efYUAec1rHd1Bgf254Zq4/TUbb3qlsQAgGK6aQSn+6LWOrrApfTEnXJ3ntQ6R9Lo5VleI2Ft0il/3/njptSPWiZimlmaYVOj2T08YJqwoTNdOZchOn/j0dOLlyNVXRqpO+sSI1UkwXE1MhfCVLo4R06Y39DVTAX3MWAAwYHfVVpvSX8SnN7pqQHnNo/HpSy763CfpRGqL8mcSRcAeI6GLgqU1a13P6yP63Ih1IjnlNa9QSq9xMycF7u7rpgL6+IjVySZAKy4uiPlWa2ukLXnw4cNfuqHJ75w01gnUhvIGAaSGEJLI1dAyJwb3fLpFkCxfctJYXVB7Zv5REiD9e4rrbUdd3OSksbrhaGhonUa+ezrVMAwzt/JA/O+L+Yg+PXnviQFl+4O2Rb5Ry9ECWXDSVCdxhc9GnZJ8rCj/n7Vjx6Z7rcUv/B8zhQMAdmpcbAAAAABJRU5ErkJggg==
openapi: 3.0.2
paths:
  tmp0:
    post:
      description: Import records from Qualys based on a previous scan run
      parameters:
      - description: The Qualys scan name.
        example: Test Scan
        in: query
        name: Scan
        required: true
        schema: {type: string}
      responses:
        '200':
          content:
            application/json:
              schema: {$ref: '#/components/schemas/tmp0'}
          description: Successful request
      summary: Qualys Latest Scan Data
  tmp1:
    post:
      description: Import records from Qualys
      parameters:
      - description: An IP Address or Range to filter for
        example: 0.0.0.0-10.255.255.255
        in: query
        name: ip_range
        required: true
        schema: {type: string}
      responses:
        '200':
          content:
            application/json:
              schema: {$ref: '#/components/schemas/tmp1'}
          description: Successful request
      summary: Qualys Get Host Detections
  tmp2:
    post:
      description: Import records from Qualys
      parameters:
      - description: The Qualys scan name.
        example: Test Scan
        in: query
        name: Scan
        required: true
        schema: {type: string}
      - description: The IP address to scan.
        example: 127.0.0.1
        in: query
        name: ip
        required: true
        schema: {type: string}
      - description: The scan option title.
        example: Initial Options
        in: query
        name: Options Title
        required: true
        schema: {type: string}
      responses:
        '200':
          content:
            application/json:
              schema: {$ref: '#/components/schemas/tmp2'}
          description: Successful request
      summary: Qualys Scan
tags:
- {name: Vulnerability & Patch Management}
