components:
  schemas:
    tmp0:
      properties:
        address: {type: string}
        city: {type: string}
        country: {type: string}
        dnssec: {type: string}
        domain_name: {type: string}
        emails: {type: string}
        name: {type: string}
        name_servers: {type: string}
        org: {type: string}
        referral_url: {type: string}
        registrar: {type: string}
        state: {type: string}
        status: {type: string}
        whois_server: {type: string}
        zipcode: {type: string}
      type: object
    tmp1:
      properties:
        address: {type: string}
        city: {type: string}
        country: {type: string}
        dnssec: {type: string}
        domain_name: {type: string}
        emails: {type: string}
        name: {type: string}
        name_servers: {type: string}
        org: {type: string}
        raw_text: {type: string}
        referral_url: {type: string}
        registrar: {type: string}
        state: {type: string}
        status: {type: string}
        whois_server: {type: string}
        zipcode: {type: string}
      type: object
  securitySchemes: {}
info:
  contact: {email: frikky@shuffler.io, name: '@frikkylikeme', url: 'https://twitter.com/frikkylikeme'}
  description: Automated generation of Swimlane WHOIS Parse
  title: Swimlane WHOIS Parse
  version: 1.0.0
  x-logo: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAFYAAABWCAYAAABVVmH3AAAGOklEQVR4nO2cz28bRRTHvzNbl7ZJkzhSFaUSYB9Q055qGlfiFheBEFVF2kOhXKr+B4FDS08kB9Q2HEL/gkhIBOQcAmcOdk8c4sQFIaGqqLGS0tAAsotjUbLdeRyC+yPenbW9s7vjdb63eDdvnj7+7nuzO7Nm6BTN0gDvQRkAxHnGwk7HTTzsBJoRzxLVoQIAy9JsmPk0I+3B8iythJ1DO9oTdgIy8SxR2Dm0K20d28lQAR0dO09jnJALOw2v0goszxKho336TNqUgk6/9HdKC7BRgwqEXQq+pgQ30JHTKTeF5lg2TzNRhQqE5NgoNSknBe7YKNZTOwUKtlugAgGB5fN0sZugAgHUWJ6lFRASfo+jm/wD+9zz026Ub6Wgm6ECfjg2wpP+VqTUsSxLs7tQt6XMsd3W9d2kxLE8S0UVcaIkb47t8s4vU9uONb6h8V2ozmrbscSxoDKRlsa2MCU7PlzI5wCMAcD66FgoexDaHjSsZiUsZHCB5Z2ODxfyNnnR2fXRzLf+ZdUoLVYQmhUJ3GwdKgCwhf5ibsCfrOzVMWCFhSR9wCacjjtD3dYBi5UPF/KfKk/MQdqXArJQoQss7nR86IdcgsdY8zclhNJ6eiypJDmJtHYsEaZkUIcLeWoJKgAwJIYLeRoq5hJe85NJW7Cihji9zyZtDxIxt0vfTdxiK0NL+RkvMaTx/QrsRULgLC6xitPx4aVbQsU4nDAxVMhnVMTaKe1qrHTvKxFTBfXFuOrrrjaOJUJeBvXw8q2LvkAFntZdECm7mdDCscJCEhdYyem413raiojo49/TGc+1N3Swbtveg4RaFxNm6cHJtzyVhlBLgajBcSoVll569AgP0m8kvMYJB+y/NRjLc5B1/qDVt7aKvrVVlE69qSRe4FuM2P0l8I07AIDYJ1+R+c9WHDcvVZzO32tQfMtivjye5E+eoHf9AQDg7ukzELGYstiB1lhjec4hCTa5df1D+aPAxfwKmJr9CXurVeyrPPuu7oyfs0mq19MMITCwTlDrEkZvyfrsPWnDGFrMTXLG2n6Q0re2+uKYsRjunj5jf7JHsIHUWDeo1sBroP5XEuzzZek052E6MwlYLa8Cx2q1BqgAnKEqkO+OlUG1Bo/Zfi4up1ymYLlxgLmuYOyrlLG3Wm343DxwAPfefkf+z7qWAuPn74CtWsPntP8QxP5DrvEFkMLl1G3ZOXZzXCYEDv523/F/bOupnXQsBcbyXANU0fcqrMFjTUH9P7Eiu1aQLquvj44xQWIBAIzHj9G3tqoGqgIpB2v8OP/C38Q4rMFjoD09LcdihnGcXy9MyM55mD51rmdjo9zzx4Y0VpBQAcVgjeU5wDIBAKL35W2Hxke8BeXGDJ9elDasX989PwiQ7XRNxGKBQwVU1dgnJoyftp1qxUcA5s9kw62pHVmYTQDG0y/hr5Gj+HPkaHuDhd286l3fqcOrlhtcADiy8CV5vpPyCNbTLS3/5fvAgDYtKifvQN2tabtq+5qllUKp2Q4fmIgYELsXdhqAF7BX0kki+VYf1ZKWAapmgJo/KwxtyPtSxExxgJv+bo4TFjK4mso7nkCPioBxXOmgYTWvhkA3FlcY25NQFa8uuUuJ+eZSXe686Eo6KYBLquIBblBrEzpd+julfIsjm15aYODjXuPIoZaTvjcpXRxbF10+cVZY8LQQJ4e6OaNL55fJ1025fLrY0sNwUUMcU6mK4wlULQNswGNazUmX5uU4wI3iJGNwfervcukngFiwrznpDhYAcK3o+FIdWWaFrp50Xganzafb3gOVbjXWVldTJSHwkd0hOdS/xxEGVAUK/MWHet0lEnm6csJ5px9VxwAW3u9vdUQpaEdhlQAAgJkCi9/2EkGrHzTTQh6dWpc22zj1kJlSFWnXsQAAKoMdHFQZcdexEF+ohgp0vWPNJFi85Efk7gWrqEk5qQvBmgRA+aW/U11WY60iWJyDxSt+j9RFYCkD1v96UKN1RynwuZ7aKfqODQEqEHWwIUEFIguWpsKECkSyxprxILq+m6IFNmSXPq+IlAKq6AQViApYdlC7V0c7HKyZ0s2pdXVujdUUaF2d6VjNoQIdB9a63QlQAa3BUqXhI9avbE2qu0WbBNrsyB/8/Q8Csyocc8qh0wAAAABJRU5ErkJggg==
openapi: 3.0.2
paths:
  tmp0:
    post:
      description: Parse WHOIS Text
      parameters:
      - description: WHOIS Domain
        example: ''
        in: query
        name: Domain
        required: true
        schema: {type: string}
      - description: WHOIS Text
        example: ''
        in: query
        name: Text
        required: true
        schema: {type: string}
      responses:
        '200':
          content:
            application/json:
              schema: {$ref: '#/components/schemas/tmp0'}
          description: Successful request
      summary: Parse WHOIS Text
  tmp1:
    post:
      description: Perform a WHOIS Lookup on a Domain
      parameters:
      - description: 'Domain of Site to Lookup. Note: This requires port 43 to be
          allowed.'
        example: ''
        in: query
        name: Domain
        required: true
        schema: {type: string}
      responses:
        '200':
          content:
            application/json:
              schema: {$ref: '#/components/schemas/tmp1'}
          description: Successful request
      summary: WHOIS Lookup
tags:
- {name: Communication}
